//! ContactMessage DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ContactMessage;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ContactMessage
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateContactMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub notified: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ContactMessage
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateContactMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub notified: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ContactMessage
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchContactMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notified: Option<bool>,
}

impl PatchContactMessageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.name.is_some() || self.email.is_some() || self.message.is_some() || self.notified.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ContactMessage entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContactMessageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub notified: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ContactMessage entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContactMessageListResponseDto {
    /// List of items
    pub items: Vec<ContactMessageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ContactMessageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ContactMessageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContactMessageSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub name: Option<String>,
    pub email: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ContactMessage> for ContactMessageResponseDto {
    fn from(entity: ContactMessage) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            name: entity.name,
            email: entity.email,
            message: entity.message,
            notified: entity.notified,
            metadata: entity.metadata,
        }
    }
}

impl From<ContactMessage> for ContactMessageSummaryDto {
    fn from(entity: ContactMessage) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            name: entity.name,
            email: entity.email,
            created_at,
        }
    }
}

impl From<CreateContactMessageDto> for ContactMessage {
    fn from(dto: CreateContactMessageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            name: dto.name,
            email: dto.email,
            message: dto.message,
            notified: dto.notified,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ContactMessage> for ContactMessageResponseDto {
    fn from(entity: &ContactMessage) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            name: entity.name.clone(),
            email: entity.email.clone(),
            message: entity.message.clone(),
            notified: entity.notified.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateContactMessageDto> for ContactMessage {
    fn from_create_dto(dto: CreateContactMessageDto) -> backbone_core::ServiceResult<Self> {
        Ok(ContactMessage::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateContactMessageDto> for ContactMessage {
    fn apply_update(mut self, dto: UpdateContactMessageDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.name = dto.name;
        self.email = dto.email;
        self.message = dto.message;
        self.notified = dto.notified;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ContactMessage here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

