//! Menu DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Menu;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WebsiteVisibility;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Menu
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMenuDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "new_window")]
    pub new_window: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub visibility: WebsiteVisibility,
    #[serde(alias = "required_member_roles")]
    pub required_member_roles: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_mega_menu")]
    pub is_mega_menu: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Menu
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMenuDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "new_window")]
    pub new_window: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub visibility: WebsiteVisibility,
    #[serde(alias = "required_member_roles")]
    pub required_member_roles: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_mega_menu")]
    pub is_mega_menu: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Menu
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMenuDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_window")]
    pub new_window: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visibility: Option<WebsiteVisibility>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "required_member_roles")]
    pub required_member_roles: Option<Vec<String>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_mega_menu")]
    pub is_mega_menu: Option<bool>,
}

impl PatchMenuDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.parent_id.is_some() || self.name.is_some() || self.page_id.is_some() || self.url.is_some() || self.new_window.is_some() || self.sequence.is_some() || self.visibility.is_some() || self.required_member_roles.is_some() || self.is_mega_menu.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Menu entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MenuResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub page_id: Option<Uuid>,
    pub url: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub new_window: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub visibility: WebsiteVisibility,
    pub required_member_roles: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_mega_menu: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Menu entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MenuListResponseDto {
    /// List of items
    pub items: Vec<MenuResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MenuListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MenuResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MenuSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub parent_id: Option<Uuid>,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Menu> for MenuResponseDto {
    fn from(entity: Menu) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            parent_id: entity.parent_id,
            name: entity.name,
            page_id: entity.page_id,
            url: entity.url,
            new_window: entity.new_window,
            sequence: entity.sequence,
            visibility: entity.visibility,
            required_member_roles: entity.required_member_roles,
            is_mega_menu: entity.is_mega_menu,
            metadata: entity.metadata,
        }
    }
}

impl From<Menu> for MenuSummaryDto {
    fn from(entity: Menu) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            parent_id: entity.parent_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateMenuDto> for Menu {
    fn from(dto: CreateMenuDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            parent_id: dto.parent_id,
            name: dto.name,
            page_id: dto.page_id,
            url: dto.url,
            new_window: dto.new_window,
            sequence: dto.sequence,
            visibility: dto.visibility,
            required_member_roles: dto.required_member_roles,
            is_mega_menu: dto.is_mega_menu,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Menu> for MenuResponseDto {
    fn from(entity: &Menu) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            parent_id: entity.parent_id.clone(),
            name: entity.name.clone(),
            page_id: entity.page_id.clone(),
            url: entity.url.clone(),
            new_window: entity.new_window.clone(),
            sequence: entity.sequence.clone(),
            visibility: entity.visibility.clone(),
            required_member_roles: entity.required_member_roles.clone(),
            is_mega_menu: entity.is_mega_menu.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMenuDto> for Menu {
    fn from_create_dto(dto: CreateMenuDto) -> backbone_core::ServiceResult<Self> {
        Ok(Menu::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMenuDto> for Menu {
    fn apply_update(mut self, dto: UpdateMenuDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.parent_id = dto.parent_id;
        self.name = dto.name;
        self.page_id = dto.page_id;
        self.url = dto.url;
        self.new_window = dto.new_window;
        self.sequence = dto.sequence;
        self.visibility = dto.visibility;
        self.required_member_roles = dto.required_member_roles;
        self.is_mega_menu = dto.is_mega_menu;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Menu here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

