//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod contact_message_dto;
pub mod menu_dto;
pub mod menu_block_dto;
pub mod page_dto;
pub mod page_block_dto;
pub mod redirect_dto;
pub mod visitor_dto;
pub mod visitor_track_dto;
pub mod website_dto;
pub mod website_audit_log_dto;
pub mod website_member_dto;

// Re-exports
pub use contact_message_dto::{
    CreateContactMessageDto,
    UpdateContactMessageDto,
    PatchContactMessageDto,
    ContactMessageResponseDto,
    ContactMessageListResponseDto,
    ContactMessageSummaryDto,
};
pub use menu_dto::{
    CreateMenuDto,
    UpdateMenuDto,
    PatchMenuDto,
    MenuResponseDto,
    MenuListResponseDto,
    MenuSummaryDto,
};
pub use menu_block_dto::{
    CreateMenuBlockDto,
    UpdateMenuBlockDto,
    PatchMenuBlockDto,
    MenuBlockResponseDto,
    MenuBlockListResponseDto,
    MenuBlockSummaryDto,
};
pub use page_dto::{
    CreatePageDto,
    UpdatePageDto,
    PatchPageDto,
    PageResponseDto,
    PageListResponseDto,
    PageSummaryDto,
};
pub use page_block_dto::{
    CreatePageBlockDto,
    UpdatePageBlockDto,
    PatchPageBlockDto,
    PageBlockResponseDto,
    PageBlockListResponseDto,
    PageBlockSummaryDto,
};
pub use redirect_dto::{
    CreateRedirectDto,
    UpdateRedirectDto,
    PatchRedirectDto,
    RedirectResponseDto,
    RedirectListResponseDto,
    RedirectSummaryDto,
};
pub use visitor_dto::{
    CreateVisitorDto,
    UpdateVisitorDto,
    PatchVisitorDto,
    VisitorResponseDto,
    VisitorListResponseDto,
    VisitorSummaryDto,
};
pub use visitor_track_dto::{
    CreateVisitorTrackDto,
    UpdateVisitorTrackDto,
    PatchVisitorTrackDto,
    VisitorTrackResponseDto,
    VisitorTrackListResponseDto,
    VisitorTrackSummaryDto,
};
pub use website_dto::{
    CreateWebsiteDto,
    UpdateWebsiteDto,
    PatchWebsiteDto,
    WebsiteResponseDto,
    WebsiteListResponseDto,
    WebsiteSummaryDto,
};
pub use website_audit_log_dto::{
    CreateWebsiteAuditLogDto,
    UpdateWebsiteAuditLogDto,
    PatchWebsiteAuditLogDto,
    WebsiteAuditLogResponseDto,
    WebsiteAuditLogListResponseDto,
    WebsiteAuditLogSummaryDto,
};
pub use website_member_dto::{
    CreateWebsiteMemberDto,
    UpdateWebsiteMemberDto,
    PatchWebsiteMemberDto,
    WebsiteMemberResponseDto,
    WebsiteMemberListResponseDto,
    WebsiteMemberSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
