//! PageBlock DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PageBlock;
use crate::domain::entity::WebsitePageBlockKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PageBlock
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePageBlockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "page_id")]
    pub page_id: Uuid,
    pub kind: WebsitePageBlockKind,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub position: i32,
    pub payload: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PageBlock
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePageBlockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "page_id")]
    pub page_id: Uuid,
    pub kind: WebsitePageBlockKind,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub position: i32,
    pub payload: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PageBlock
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPageBlockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<WebsitePageBlockKind>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
}

impl PatchPageBlockDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.page_id.is_some() || self.kind.is_some() || self.position.is_some() || self.payload.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PageBlock entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageBlockResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub page_id: Uuid,
    pub kind: WebsitePageBlockKind,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub position: i32,
    pub payload: serde_json::Value,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PageBlock entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageBlockListResponseDto {
    /// List of items
    pub items: Vec<PageBlockResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PageBlockListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PageBlockResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageBlockSummaryDto {
    pub id: Uuid,
    pub page_id: Uuid,
    pub kind: WebsitePageBlockKind,
    pub position: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PageBlock> for PageBlockResponseDto {
    fn from(entity: PageBlock) -> Self {
        Self {
            id: entity.id,
            page_id: entity.page_id,
            kind: entity.kind,
            position: entity.position,
            payload: entity.payload,
        }
    }
}

impl From<PageBlock> for PageBlockSummaryDto {
    fn from(entity: PageBlock) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            page_id: entity.page_id,
            kind: entity.kind,
            position: entity.position,
            created_at,
        }
    }
}

impl From<CreatePageBlockDto> for PageBlock {
    fn from(dto: CreatePageBlockDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            page_id: dto.page_id,
            kind: dto.kind,
            position: dto.position,
            payload: dto.payload,
        }
    }
}

impl From<&PageBlock> for PageBlockResponseDto {
    fn from(entity: &PageBlock) -> Self {
        Self {
            id: entity.id.clone(),
            page_id: entity.page_id.clone(),
            kind: entity.kind.clone(),
            position: entity.position.clone(),
            payload: entity.payload.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePageBlockDto> for PageBlock {
    fn from_create_dto(dto: CreatePageBlockDto) -> backbone_core::ServiceResult<Self> {
        Ok(PageBlock::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePageBlockDto> for PageBlock {
    fn apply_update(mut self, dto: UpdatePageBlockDto) -> backbone_core::ServiceResult<Self> {
        self.page_id = dto.page_id;
        self.kind = dto.kind;
        self.position = dto.position;
        self.payload = dto.payload;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PageBlock here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

