//! Page DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Page;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WebsiteVisibility;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Page
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "seo_name")]
    pub seo_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_publish")]
    pub date_publish: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "website_indexed")]
    pub website_indexed: bool,
    pub visibility: WebsiteVisibility,
    #[serde(alias = "required_member_roles")]
    pub required_member_roles: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_from")]
    pub forked_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_at")]
    pub forked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_by")]
    pub forked_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Page
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "seo_name")]
    pub seo_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_publish")]
    pub date_publish: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "website_indexed")]
    pub website_indexed: bool,
    pub visibility: WebsiteVisibility,
    #[serde(alias = "required_member_roles")]
    pub required_member_roles: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_from")]
    pub forked_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_at")]
    pub forked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "forked_by")]
    pub forked_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Page
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "seo_name")]
    pub seo_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_published")]
    pub is_published: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_publish")]
    pub date_publish: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_indexed")]
    pub website_indexed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visibility: Option<WebsiteVisibility>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "required_member_roles")]
    pub required_member_roles: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "forked_from")]
    pub forked_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "forked_at")]
    pub forked_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "forked_by")]
    pub forked_by: Option<Uuid>,
}

impl PatchPageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.key.is_some() || self.website_id.is_some() || self.url.is_some() || self.title.is_some() || self.seo_name.is_some() || self.is_published.is_some() || self.date_publish.is_some() || self.website_indexed.is_some() || self.visibility.is_some() || self.required_member_roles.is_some() || self.forked_from.is_some() || self.forked_at.is_some() || self.forked_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Page entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub key: String,
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub seo_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_published: bool,
    pub date_publish: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub website_indexed: bool,
    pub visibility: WebsiteVisibility,
    pub required_member_roles: Vec<String>,
    pub forked_from: Option<Uuid>,
    pub forked_at: Option<DateTime<Utc>>,
    pub forked_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Page entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageListResponseDto {
    /// List of items
    pub items: Vec<PageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PageSummaryDto {
    pub id: Uuid,
    pub key: String,
    pub website_id: Option<Uuid>,
    pub url: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Page> for PageResponseDto {
    fn from(entity: Page) -> Self {
        Self {
            id: entity.id,
            key: entity.key,
            website_id: entity.website_id,
            url: entity.url,
            title: entity.title,
            seo_name: entity.seo_name,
            is_published: entity.is_published,
            date_publish: entity.date_publish,
            website_indexed: entity.website_indexed,
            visibility: entity.visibility,
            required_member_roles: entity.required_member_roles,
            forked_from: entity.forked_from,
            forked_at: entity.forked_at,
            forked_by: entity.forked_by,
            metadata: entity.metadata,
        }
    }
}

impl From<Page> for PageSummaryDto {
    fn from(entity: Page) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            key: entity.key,
            website_id: entity.website_id,
            url: entity.url,
            created_at,
        }
    }
}

impl From<CreatePageDto> for Page {
    fn from(dto: CreatePageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            key: dto.key,
            website_id: dto.website_id,
            url: dto.url,
            title: dto.title,
            seo_name: dto.seo_name,
            is_published: dto.is_published,
            date_publish: dto.date_publish,
            website_indexed: dto.website_indexed,
            visibility: dto.visibility,
            required_member_roles: dto.required_member_roles,
            forked_from: dto.forked_from,
            forked_at: dto.forked_at,
            forked_by: dto.forked_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Page> for PageResponseDto {
    fn from(entity: &Page) -> Self {
        Self {
            id: entity.id.clone(),
            key: entity.key.clone(),
            website_id: entity.website_id.clone(),
            url: entity.url.clone(),
            title: entity.title.clone(),
            seo_name: entity.seo_name.clone(),
            is_published: entity.is_published.clone(),
            date_publish: entity.date_publish.clone(),
            website_indexed: entity.website_indexed.clone(),
            visibility: entity.visibility.clone(),
            required_member_roles: entity.required_member_roles.clone(),
            forked_from: entity.forked_from.clone(),
            forked_at: entity.forked_at.clone(),
            forked_by: entity.forked_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePageDto> for Page {
    fn from_create_dto(dto: CreatePageDto) -> backbone_core::ServiceResult<Self> {
        Ok(Page::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePageDto> for Page {
    fn apply_update(mut self, dto: UpdatePageDto) -> backbone_core::ServiceResult<Self> {
        self.key = dto.key;
        self.website_id = dto.website_id;
        self.url = dto.url;
        self.title = dto.title;
        self.seo_name = dto.seo_name;
        self.is_published = dto.is_published;
        self.date_publish = dto.date_publish;
        self.website_indexed = dto.website_indexed;
        self.visibility = dto.visibility;
        self.required_member_roles = dto.required_member_roles;
        self.forked_from = dto.forked_from;
        self.forked_at = dto.forked_at;
        self.forked_by = dto.forked_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Page here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

