//! Redirect DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Redirect;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WebsiteRedirectType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Redirect
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRedirectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "url_from")]
    pub url_from: String,
    #[serde(alias = "redirect_type")]
    pub redirect_type: WebsiteRedirectType,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "url_to")]
    pub url_to: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Redirect
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRedirectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "url_from")]
    pub url_from: String,
    #[serde(alias = "redirect_type")]
    pub redirect_type: WebsiteRedirectType,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "url_to")]
    pub url_to: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Redirect
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRedirectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "url_from")]
    pub url_from: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "redirect_type")]
    pub redirect_type: Option<WebsiteRedirectType>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "url_to")]
    pub url_to: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchRedirectDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.url_from.is_some() || self.redirect_type.is_some() || self.url_to.is_some() || self.description.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Redirect entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RedirectResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url_from: String,
    pub redirect_type: WebsiteRedirectType,
    pub url_to: Option<String>,
    pub description: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Redirect entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RedirectListResponseDto {
    /// List of items
    pub items: Vec<RedirectResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RedirectListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RedirectResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RedirectSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub url_from: String,
    pub redirect_type: WebsiteRedirectType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Redirect> for RedirectResponseDto {
    fn from(entity: Redirect) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            url_from: entity.url_from,
            redirect_type: entity.redirect_type,
            url_to: entity.url_to,
            description: entity.description,
            metadata: entity.metadata,
        }
    }
}

impl From<Redirect> for RedirectSummaryDto {
    fn from(entity: Redirect) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            url_from: entity.url_from,
            redirect_type: entity.redirect_type,
            created_at,
        }
    }
}

impl From<CreateRedirectDto> for Redirect {
    fn from(dto: CreateRedirectDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            url_from: dto.url_from,
            redirect_type: dto.redirect_type,
            url_to: dto.url_to,
            description: dto.description,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Redirect> for RedirectResponseDto {
    fn from(entity: &Redirect) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            url_from: entity.url_from.clone(),
            redirect_type: entity.redirect_type.clone(),
            url_to: entity.url_to.clone(),
            description: entity.description.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRedirectDto> for Redirect {
    fn from_create_dto(dto: CreateRedirectDto) -> backbone_core::ServiceResult<Self> {
        Ok(Redirect::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRedirectDto> for Redirect {
    fn apply_update(mut self, dto: UpdateRedirectDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.url_from = dto.url_from;
        self.redirect_type = dto.redirect_type;
        self.url_to = dto.url_to;
        self.description = dto.description;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Redirect here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

