//! Visitor DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Visitor;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WebsiteVisitorKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Visitor
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateVisitorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "access_token")]
    pub access_token: String,
    pub kind: WebsiteVisitorKind,
    #[cfg_attr(feature = "validation", validate(length(max = 128)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub digest: String,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "digest_algo")]
    pub digest_algo: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "visit_count")]
    pub visit_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "last_connection_at")]
    pub last_connection_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Visitor
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateVisitorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "access_token")]
    pub access_token: String,
    pub kind: WebsiteVisitorKind,
    #[cfg_attr(feature = "validation", validate(length(max = 128)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub digest: String,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "digest_algo")]
    pub digest_algo: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "visit_count")]
    pub visit_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "last_connection_at")]
    pub last_connection_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Visitor
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchVisitorDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "access_token")]
    pub access_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<WebsiteVisitorKind>,
    #[cfg_attr(feature = "validation", validate(length(max = 128)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "digest_algo")]
    pub digest_algo: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visit_count")]
    pub visit_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_connection_at")]
    pub last_connection_at: Option<DateTime<Utc>>,
}

impl PatchVisitorDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.access_token.is_some() || self.kind.is_some() || self.digest.is_some() || self.digest_algo.is_some() || self.portal_user_id.is_some() || self.country_code.is_some() || self.visit_count.is_some() || self.last_connection_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Visitor entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub access_token: String,
    pub kind: WebsiteVisitorKind,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub digest: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub digest_algo: String,
    pub portal_user_id: Option<Uuid>,
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub visit_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub last_connection_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Visitor entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorListResponseDto {
    /// List of items
    pub items: Vec<VisitorResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl VisitorListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<VisitorResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub access_token: String,
    pub kind: WebsiteVisitorKind,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Visitor> for VisitorResponseDto {
    fn from(entity: Visitor) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            access_token: entity.access_token,
            kind: entity.kind,
            digest: entity.digest,
            digest_algo: entity.digest_algo,
            portal_user_id: entity.portal_user_id,
            country_code: entity.country_code,
            visit_count: entity.visit_count,
            last_connection_at: entity.last_connection_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Visitor> for VisitorSummaryDto {
    fn from(entity: Visitor) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            access_token: entity.access_token,
            kind: entity.kind,
            created_at,
        }
    }
}

impl From<CreateVisitorDto> for Visitor {
    fn from(dto: CreateVisitorDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            access_token: dto.access_token,
            kind: dto.kind,
            digest: dto.digest,
            digest_algo: dto.digest_algo,
            portal_user_id: dto.portal_user_id,
            country_code: dto.country_code,
            visit_count: dto.visit_count,
            last_connection_at: dto.last_connection_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Visitor> for VisitorResponseDto {
    fn from(entity: &Visitor) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            access_token: entity.access_token.clone(),
            kind: entity.kind.clone(),
            digest: entity.digest.clone(),
            digest_algo: entity.digest_algo.clone(),
            portal_user_id: entity.portal_user_id.clone(),
            country_code: entity.country_code.clone(),
            visit_count: entity.visit_count.clone(),
            last_connection_at: entity.last_connection_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateVisitorDto> for Visitor {
    fn from_create_dto(dto: CreateVisitorDto) -> backbone_core::ServiceResult<Self> {
        Ok(Visitor::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateVisitorDto> for Visitor {
    fn apply_update(mut self, dto: UpdateVisitorDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.access_token = dto.access_token;
        self.kind = dto.kind;
        self.digest = dto.digest;
        self.digest_algo = dto.digest_algo;
        self.portal_user_id = dto.portal_user_id;
        self.country_code = dto.country_code;
        self.visit_count = dto.visit_count;
        self.last_connection_at = dto.last_connection_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Visitor here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

