//! VisitorTrack DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::VisitorTrack;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new VisitorTrack
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateVisitorTrackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "visited_at")]
    pub visited_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a VisitorTrack
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateVisitorTrackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "visited_at")]
    pub visited_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a VisitorTrack
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchVisitorTrackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_id")]
    pub visitor_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visited_at")]
    pub visited_at: Option<DateTime<Utc>>,
}

impl PatchVisitorTrackDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.visitor_id.is_some() || self.page_id.is_some() || self.url.is_some() || self.visited_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for VisitorTrack entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorTrackResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub visitor_id: Uuid,
    pub page_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub visited_at: DateTime<Utc>,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for VisitorTrack entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorTrackListResponseDto {
    /// List of items
    pub items: Vec<VisitorTrackResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl VisitorTrackListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<VisitorTrackResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct VisitorTrackSummaryDto {
    pub id: Uuid,
    pub visitor_id: Uuid,
    pub page_id: Option<Uuid>,
    pub url: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<VisitorTrack> for VisitorTrackResponseDto {
    fn from(entity: VisitorTrack) -> Self {
        Self {
            id: entity.id,
            visitor_id: entity.visitor_id,
            page_id: entity.page_id,
            url: entity.url,
            visited_at: entity.visited_at,
        }
    }
}

impl From<VisitorTrack> for VisitorTrackSummaryDto {
    fn from(entity: VisitorTrack) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            visitor_id: entity.visitor_id,
            page_id: entity.page_id,
            url: entity.url,
            created_at,
        }
    }
}

impl From<CreateVisitorTrackDto> for VisitorTrack {
    fn from(dto: CreateVisitorTrackDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            visitor_id: dto.visitor_id,
            page_id: dto.page_id,
            url: dto.url,
            visited_at: dto.visited_at,
        }
    }
}

impl From<&VisitorTrack> for VisitorTrackResponseDto {
    fn from(entity: &VisitorTrack) -> Self {
        Self {
            id: entity.id.clone(),
            visitor_id: entity.visitor_id.clone(),
            page_id: entity.page_id.clone(),
            url: entity.url.clone(),
            visited_at: entity.visited_at.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateVisitorTrackDto> for VisitorTrack {
    fn from_create_dto(dto: CreateVisitorTrackDto) -> backbone_core::ServiceResult<Self> {
        Ok(VisitorTrack::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateVisitorTrackDto> for VisitorTrack {
    fn apply_update(mut self, dto: UpdateVisitorTrackDto) -> backbone_core::ServiceResult<Self> {
        self.visitor_id = dto.visitor_id;
        self.page_id = dto.page_id;
        self.url = dto.url;
        self.visited_at = dto.visited_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to VisitorTrack here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

