//! WebsiteMember DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WebsiteMember;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WebsiteMemberRole;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WebsiteMember
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWebsiteMemberDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "portal_user_id")]
    pub portal_user_id: Uuid,
    pub role: WebsiteMemberRole,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WebsiteMember
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWebsiteMemberDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "portal_user_id")]
    pub portal_user_id: Uuid,
    pub role: WebsiteMemberRole,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WebsiteMember
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWebsiteMemberDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<WebsiteMemberRole>,
}

impl PatchWebsiteMemberDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.portal_user_id.is_some() || self.role.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WebsiteMember entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteMemberResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub portal_user_id: Uuid,
    pub role: WebsiteMemberRole,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WebsiteMember entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteMemberListResponseDto {
    /// List of items
    pub items: Vec<WebsiteMemberResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WebsiteMemberListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WebsiteMemberResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteMemberSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub portal_user_id: Uuid,
    pub role: WebsiteMemberRole,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WebsiteMember> for WebsiteMemberResponseDto {
    fn from(entity: WebsiteMember) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            portal_user_id: entity.portal_user_id,
            role: entity.role,
            metadata: entity.metadata,
        }
    }
}

impl From<WebsiteMember> for WebsiteMemberSummaryDto {
    fn from(entity: WebsiteMember) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            portal_user_id: entity.portal_user_id,
            role: entity.role,
            created_at,
        }
    }
}

impl From<CreateWebsiteMemberDto> for WebsiteMember {
    fn from(dto: CreateWebsiteMemberDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            portal_user_id: dto.portal_user_id,
            role: dto.role,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WebsiteMember> for WebsiteMemberResponseDto {
    fn from(entity: &WebsiteMember) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            portal_user_id: entity.portal_user_id.clone(),
            role: entity.role.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWebsiteMemberDto> for WebsiteMember {
    fn from_create_dto(dto: CreateWebsiteMemberDto) -> backbone_core::ServiceResult<Self> {
        Ok(WebsiteMember::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWebsiteMemberDto> for WebsiteMember {
    fn apply_update(mut self, dto: UpdateWebsiteMemberDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.portal_user_id = dto.portal_user_id;
        self.role = dto.role;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WebsiteMember here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

