//! Website DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Website;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Website
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWebsiteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "public_user_id")]
    pub public_user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "default_lang_code")]
    pub default_lang_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "homepage_url")]
    pub homepage_url: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "robots_txt")]
    pub robots_txt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "social_links")]
    pub social_links: Option<serde_json::Value>,
    #[serde(alias = "contact_recipients")]
    pub contact_recipients: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Website
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWebsiteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "public_user_id")]
    pub public_user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "default_lang_code")]
    pub default_lang_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "homepage_url")]
    pub homepage_url: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "robots_txt")]
    pub robots_txt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "social_links")]
    pub social_links: Option<serde_json::Value>,
    #[serde(alias = "contact_recipients")]
    pub contact_recipients: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Website
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWebsiteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "public_user_id")]
    pub public_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_lang_code")]
    pub default_lang_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "homepage_url")]
    pub homepage_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "robots_txt")]
    pub robots_txt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "social_links")]
    pub social_links: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "contact_recipients")]
    pub contact_recipients: Option<Vec<String>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
}

impl PatchWebsiteDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.domain.is_some() || self.company_id.is_some() || self.public_user_id.is_some() || self.default_lang_code.is_some() || self.homepage_url.is_some() || self.robots_txt.is_some() || self.social_links.is_some() || self.contact_recipients.is_some() || self.sequence.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Website entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub domain: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub public_user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub default_lang_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub homepage_url: String,
    pub robots_txt: Option<String>,
    pub social_links: Option<serde_json::Value>,
    pub contact_recipients: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Website entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteListResponseDto {
    /// List of items
    pub items: Vec<WebsiteResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WebsiteListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WebsiteResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub domain: Option<String>,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Website> for WebsiteResponseDto {
    fn from(entity: Website) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            domain: entity.domain,
            company_id: entity.company_id,
            public_user_id: entity.public_user_id,
            default_lang_code: entity.default_lang_code,
            homepage_url: entity.homepage_url,
            robots_txt: entity.robots_txt,
            social_links: entity.social_links,
            contact_recipients: entity.contact_recipients,
            sequence: entity.sequence,
            metadata: entity.metadata,
        }
    }
}

impl From<Website> for WebsiteSummaryDto {
    fn from(entity: Website) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            domain: entity.domain,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreateWebsiteDto> for Website {
    fn from(dto: CreateWebsiteDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            domain: dto.domain,
            company_id: dto.company_id,
            public_user_id: dto.public_user_id,
            default_lang_code: dto.default_lang_code,
            homepage_url: dto.homepage_url,
            robots_txt: dto.robots_txt,
            social_links: dto.social_links,
            contact_recipients: dto.contact_recipients,
            sequence: dto.sequence,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Website> for WebsiteResponseDto {
    fn from(entity: &Website) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            domain: entity.domain.clone(),
            company_id: entity.company_id.clone(),
            public_user_id: entity.public_user_id.clone(),
            default_lang_code: entity.default_lang_code.clone(),
            homepage_url: entity.homepage_url.clone(),
            robots_txt: entity.robots_txt.clone(),
            social_links: entity.social_links.clone(),
            contact_recipients: entity.contact_recipients.clone(),
            sequence: entity.sequence.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWebsiteDto> for Website {
    fn from_create_dto(dto: CreateWebsiteDto) -> backbone_core::ServiceResult<Self> {
        Ok(Website::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWebsiteDto> for Website {
    fn apply_update(mut self, dto: UpdateWebsiteDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.domain = dto.domain;
        self.company_id = dto.company_id;
        self.public_user_id = dto.public_user_id;
        self.default_lang_code = dto.default_lang_code;
        self.homepage_url = dto.homepage_url;
        self.robots_txt = dto.robots_txt;
        self.social_links = dto.social_links;
        self.contact_recipients = dto.contact_recipients;
        self.sequence = dto.sequence;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Website here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

