//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod contact_message_specification;
pub mod menu_specification;
pub mod menu_block_specification;
pub mod page_specification;
pub mod page_block_specification;
pub mod redirect_specification;
pub mod visitor_specification;
pub mod visitor_track_specification;
pub mod website_specification;
pub mod website_audit_log_specification;
pub mod website_member_specification;

// <<< CUSTOM
// END CUSTOM
