//! Domain policy for MenuBlock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::MenuBlock;

/// Domain policy for MenuBlock — permits all operations (no business invariants).
///
/// NOTE: `DomainPolicy` is advisory only — it is NOT invoked by the generic
/// CRUD pipeline. `GenericCrudService` enforces invariants via a different
/// trait, `ServiceLifecycle` (`before_create` / `before_update`). So implementing
/// a real `DomainPolicy` here is not yet wired to runtime. For actual per-write
/// enforcement, implement `backbone_core::ServiceLifecycle<MenuBlock>` on a custom
/// service. `PermitAllPolicy` is the safe default until then.
pub type MenuBlockDomainPolicy = PermitAllPolicy<MenuBlock>;

// <<< CUSTOM
// END CUSTOM
