//! Application service for ContactMessage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `contact_message_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateContactMessageDto, UpdateContactMessageDto};
use crate::domain::entity::ContactMessage;
use crate::infrastructure::persistence::ContactMessageRepository;

/// Application service for ContactMessage entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `contact_message_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ContactMessageServiceCustom {
///     inner: Arc<ContactMessageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ContactMessageService = GenericCrudService<
    ContactMessage,
    CreateContactMessageDto,
    UpdateContactMessageDto,
    ContactMessageRepository,
>;

// <<< CUSTOM
// END CUSTOM
