//! Service error types
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Re-exported from backbone-core so that existing `super::error::ServiceError`
//! import paths continue to work without change.

pub use backbone_core::{ServiceError, ServiceResult};
