//! Application service for MenuBlock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `menu_block_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMenuBlockDto, UpdateMenuBlockDto};
use crate::domain::entity::MenuBlock;
use crate::infrastructure::persistence::MenuBlockRepository;

/// Application service for MenuBlock entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `menu_block_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MenuBlockServiceCustom {
///     inner: Arc<MenuBlockService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MenuBlockService = GenericCrudService<
    MenuBlock,
    CreateMenuBlockDto,
    UpdateMenuBlockDto,
    MenuBlockRepository,
>;

// <<< CUSTOM
// END CUSTOM
