//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod contact_message_service;
pub mod menu_service;
pub mod menu_block_service;
pub mod page_service;
pub mod page_block_service;
pub mod redirect_service;
pub mod visitor_service;
pub mod visitor_track_service;
pub mod website_service;
pub mod website_audit_log_service;
pub mod website_member_service;

// <<< CUSTOM
pub mod intake_contact;
pub mod intake_engine;
pub mod lang_matcher;
pub mod notifier_port;
pub mod principal_port;
pub mod slug;
pub mod specificity;
pub mod versioning_service;
pub mod visitor_gc;
pub mod website_error;
pub mod website_surface;

pub use intake_contact::{ContactIntake, ContactMessageView};
pub use intake_engine::{
    IntakeEngine, IntakeOutcome, IntakeRatePolicy, TurnstileClient, TurnstileConfig,
};
pub use lang_matcher::{
    apply_matcher, RedirectAnswer as MatcherRedirectAnswer, MatchInput, ResolveAnswer,
};
pub use principal_port::{RefusingPrincipalVerifier, WebsitePrincipal, WebsitePrincipalVerifier};
pub use slug::{slug_from, SlugId};
pub use specificity::{
    live_scope, prefer_specific, page_entity_by_id, resolve_page_by_url, resolve_sitemap_page,
    resolve_specific, Resolution, ResolvedPage, ScopeFragment,
};
pub use versioning_service::{delete_generic_with_fanout, fork_to_website, FanoutDeletion, ForkOutcome};
pub use visitor_gc::{sweep_partnerless_visitors, SweepSummary};
pub use website_error::{map_unique_violation, WebsiteError};
pub use website_surface::{PgWebsiteSurface, WebsiteSurface};
// END CUSTOM

pub use contact_message_service::ContactMessageService;
pub use menu_service::MenuService;
pub use menu_block_service::MenuBlockService;
pub use page_service::PageService;
pub use page_block_service::PageBlockService;
pub use redirect_service::RedirectService;
pub use visitor_service::VisitorService;
pub use visitor_track_service::VisitorTrackService;
pub use website_service::WebsiteService;
pub use website_audit_log_service::WebsiteAuditLogService;
pub use website_member_service::WebsiteMemberService;
// <<< CUSTOM
pub use notifier_port::{IntakeNotifier, UnwiredIntakeNotifier};
pub use website_service::{
    normalize_host, record_audit, ActorRef, WebsiteRootService, WebsiteView,
};
// END CUSTOM
