//! Application service for PageBlock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `page_block_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePageBlockDto, UpdatePageBlockDto};
use crate::domain::entity::PageBlock;
use crate::infrastructure::persistence::PageBlockRepository;

/// Application service for PageBlock entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `page_block_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PageBlockServiceCustom {
///     inner: Arc<PageBlockService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PageBlockService = GenericCrudService<
    PageBlock,
    CreatePageBlockDto,
    UpdatePageBlockDto,
    PageBlockRepository,
>;

// <<< CUSTOM
// END CUSTOM
