//! Application service for VisitorTrack entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `visitor_track_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateVisitorTrackDto, UpdateVisitorTrackDto};
use crate::domain::entity::VisitorTrack;
use crate::infrastructure::persistence::VisitorTrackRepository;

/// Application service for VisitorTrack entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `visitor_track_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct VisitorTrackServiceCustom {
///     inner: Arc<VisitorTrackService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type VisitorTrackService = GenericCrudService<
    VisitorTrack,
    CreateVisitorTrackDto,
    UpdateVisitorTrackDto,
    VisitorTrackRepository,
>;

// <<< CUSTOM
// END CUSTOM
