//! Application service for WebsiteAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `website_audit_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWebsiteAuditLogDto, UpdateWebsiteAuditLogDto};
use crate::domain::entity::WebsiteAuditLog;
use crate::infrastructure::persistence::WebsiteAuditLogRepository;

/// Application service for WebsiteAuditLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `website_audit_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WebsiteAuditLogServiceCustom {
///     inner: Arc<WebsiteAuditLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WebsiteAuditLogService = GenericCrudService<
    WebsiteAuditLog,
    CreateWebsiteAuditLogDto,
    UpdateWebsiteAuditLogDto,
    WebsiteAuditLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
