//! Application service for WebsiteMember entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `website_member_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWebsiteMemberDto, UpdateWebsiteMemberDto};
use crate::domain::entity::WebsiteMember;
use crate::infrastructure::persistence::WebsiteMemberRepository;

/// Application service for WebsiteMember entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `website_member_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WebsiteMemberServiceCustom {
///     inner: Arc<WebsiteMemberService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WebsiteMemberService = GenericCrudService<
    WebsiteMember,
    CreateWebsiteMemberDto,
    UpdateWebsiteMemberDto,
    WebsiteMemberRepository,
>;

// <<< CUSTOM
// END CUSTOM
