-- Menu Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.menus table.
-- Customize this file to add your initial data.

-- INSERT INTO website.menus (
--     id,
--     website_id,
--     parent_id,
--     name,
--     page_id,
--     url,
--     new_window,
--     sequence,
--     visibility,
--     required_member_roles,
--     is_mega_menu,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO website.menus (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

