-- PageBlock Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.page_blocks table.
-- Customize this file to add your initial data.

-- INSERT INTO website.page_blocks (
--     id,
--     page_id,
--     kind,
--     position,
--     payload
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.page_blocks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

