-- Page Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.pages table.
-- Customize this file to add your initial data.

-- INSERT INTO website.pages (
--     id,
--     key,
--     website_id,
--     url,
--     title,
--     seo_name,
--     is_published,
--     date_publish,
--     website_indexed,
--     visibility,
--     required_member_roles,
--     forked_from,
--     forked_at,
--     forked_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.pages (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

