-- Redirect Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.redirects table.
-- Customize this file to add your initial data.

-- INSERT INTO website.redirects (
--     id,
--     website_id,
--     url_from,
--     redirect_type,
--     url_to,
--     description,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.redirects (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

