-- Visitor Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.visitors table.
-- Customize this file to add your initial data.

-- INSERT INTO website.visitors (
--     id,
--     website_id,
--     access_token,
--     kind,
--     digest,
--     digest_algo,
--     portal_user_id,
--     country_code,
--     visit_count,
--     last_connection_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.visitors (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

