-- VisitorTrack Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.visitor_tracks table.
-- Customize this file to add your initial data.

-- INSERT INTO website.visitor_tracks (
--     id,
--     visitor_id,
--     page_id,
--     url,
--     visited_at
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.visitor_tracks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

