-- WebsiteMember Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.website_members table.
-- Customize this file to add your initial data.

-- INSERT INTO website.website_members (
--     id,
--     website_id,
--     portal_user_id,
--     role,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO website.website_members (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

