-- Website Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the website.websites table.
-- Customize this file to add your initial data.

-- INSERT INTO website.websites (
--     id,
--     name,
--     domain,
--     company_id,
--     public_user_id,
--     default_lang_code,
--     homepage_url,
--     robots_txt,
--     social_links,
--     contact_recipients,
--     sequence,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO website.websites (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

