-- Migration: Create visitor_tracks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.visitor_tracks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    visitor_id UUID NOT NULL,
    page_id UUID,
    url TEXT NOT NULL,
    visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_visitor_tracks_visitor_id_visited_at ON website.visitor_tracks (visitor_id, visited_at);

CREATE INDEX IF NOT EXISTS idx_visitor_tracks_url ON website.visitor_tracks (url);

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.visitor_tracks ADD CONSTRAINT fk_visitor_tracks_visitor_id FOREIGN KEY (visitor_id) REFERENCES website.visitors (id) ON DELETE CASCADE;
