-- Migration: Create redirects table
-- Generated by metaphor-schema

-- Create website_redirect_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_redirect_type') THEN
        CREATE TYPE website_redirect_type AS ENUM ('moved_301', 'found_302', 'alias_308', 'gone_404');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.redirects (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL,
    url_from TEXT NOT NULL,
    redirect_type website_redirect_type NOT NULL DEFAULT 'found_302',
    url_to TEXT,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_redirects_website_id_url_from ON website.redirects (website_id, url_from);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_redirects_metadata_gin ON website.redirects USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_redirects_metadata_deleted_at ON website.redirects ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_redirects_metadata_created_at ON website.redirects ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_redirects_metadata_updated_at ON website.redirects ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.redirects_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS redirects_insert_audit ON website.redirects;
CREATE TRIGGER redirects_insert_audit BEFORE INSERT ON website.redirects
    FOR EACH ROW EXECUTE FUNCTION website.redirects_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS redirects_update_audit ON website.redirects;
CREATE TRIGGER redirects_update_audit BEFORE UPDATE ON website.redirects
    FOR EACH ROW EXECUTE FUNCTION website.redirects_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.redirects ADD CONSTRAINT fk_redirects_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
