-- Audit Triggers Migration for website module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ContactMessage (website.contact_messages)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.contact_messages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS contact_messages_insert_audit ON website.contact_messages;
CREATE TRIGGER contact_messages_insert_audit BEFORE INSERT ON website.contact_messages
    FOR EACH ROW EXECUTE FUNCTION website.contact_messages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS contact_messages_update_audit ON website.contact_messages;
CREATE TRIGGER contact_messages_update_audit BEFORE UPDATE ON website.contact_messages
    FOR EACH ROW EXECUTE FUNCTION website.contact_messages_audit_timestamp();

-- ==============================================================================
-- Table: Menu (website.menus)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.menus_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS menus_insert_audit ON website.menus;
CREATE TRIGGER menus_insert_audit BEFORE INSERT ON website.menus
    FOR EACH ROW EXECUTE FUNCTION website.menus_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS menus_update_audit ON website.menus;
CREATE TRIGGER menus_update_audit BEFORE UPDATE ON website.menus
    FOR EACH ROW EXECUTE FUNCTION website.menus_audit_timestamp();

-- ==============================================================================
-- Table: Page (website.pages)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.pages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pages_insert_audit ON website.pages;
CREATE TRIGGER pages_insert_audit BEFORE INSERT ON website.pages
    FOR EACH ROW EXECUTE FUNCTION website.pages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pages_update_audit ON website.pages;
CREATE TRIGGER pages_update_audit BEFORE UPDATE ON website.pages
    FOR EACH ROW EXECUTE FUNCTION website.pages_audit_timestamp();

-- ==============================================================================
-- Table: Redirect (website.redirects)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.redirects_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS redirects_insert_audit ON website.redirects;
CREATE TRIGGER redirects_insert_audit BEFORE INSERT ON website.redirects
    FOR EACH ROW EXECUTE FUNCTION website.redirects_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS redirects_update_audit ON website.redirects;
CREATE TRIGGER redirects_update_audit BEFORE UPDATE ON website.redirects
    FOR EACH ROW EXECUTE FUNCTION website.redirects_audit_timestamp();

-- ==============================================================================
-- Table: Visitor (website.visitors)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.visitors_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS visitors_insert_audit ON website.visitors;
CREATE TRIGGER visitors_insert_audit BEFORE INSERT ON website.visitors
    FOR EACH ROW EXECUTE FUNCTION website.visitors_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS visitors_update_audit ON website.visitors;
CREATE TRIGGER visitors_update_audit BEFORE UPDATE ON website.visitors
    FOR EACH ROW EXECUTE FUNCTION website.visitors_audit_timestamp();

-- ==============================================================================
-- Table: Website (website.websites)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.websites_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS websites_insert_audit ON website.websites;
CREATE TRIGGER websites_insert_audit BEFORE INSERT ON website.websites
    FOR EACH ROW EXECUTE FUNCTION website.websites_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS websites_update_audit ON website.websites;
CREATE TRIGGER websites_update_audit BEFORE UPDATE ON website.websites
    FOR EACH ROW EXECUTE FUNCTION website.websites_audit_timestamp();

-- ==============================================================================
-- Table: WebsiteMember (website.website_members)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION website.website_members_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS website_members_insert_audit ON website.website_members;
CREATE TRIGGER website_members_insert_audit BEFORE INSERT ON website.website_members
    FOR EACH ROW EXECUTE FUNCTION website.website_members_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS website_members_update_audit ON website.website_members;
CREATE TRIGGER website_members_update_audit BEFORE UPDATE ON website.website_members
    FOR EACH ROW EXECUTE FUNCTION website.website_members_audit_timestamp();

