-- Migration: Create menus table
-- Generated by metaphor-schema

-- Create website_visibility enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_visibility') THEN
        CREATE TYPE website_visibility AS ENUM ('public', 'connected', 'restricted');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.menus (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL,
    parent_id UUID,
    name TEXT NOT NULL,
    page_id UUID,
    url TEXT,
    new_window BOOLEAN NOT NULL DEFAULT FALSE,
    sequence INTEGER NOT NULL DEFAULT 10,
    visibility website_visibility NOT NULL DEFAULT 'public',
    required_member_roles TEXT[] NOT NULL DEFAULT '{}',
    is_mega_menu BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_menus_website_id_parent_id_sequence ON website.menus (website_id, parent_id, sequence);

CREATE INDEX IF NOT EXISTS idx_menus_page_id ON website.menus (page_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_menus_metadata_gin ON website.menus USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_menus_metadata_deleted_at ON website.menus ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_menus_metadata_created_at ON website.menus ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_menus_metadata_updated_at ON website.menus ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.menus_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS menus_insert_audit ON website.menus;
CREATE TRIGGER menus_insert_audit BEFORE INSERT ON website.menus
    FOR EACH ROW EXECUTE FUNCTION website.menus_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS menus_update_audit ON website.menus;
CREATE TRIGGER menus_update_audit BEFORE UPDATE ON website.menus
    FOR EACH ROW EXECUTE FUNCTION website.menus_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.menus ADD CONSTRAINT fk_menus_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
ALTER TABLE website.menus ADD CONSTRAINT fk_menus_parent_id FOREIGN KEY (parent_id) REFERENCES website.menus (id) ON DELETE CASCADE;
