-- Migration: Create website_members table
-- Generated by metaphor-schema

-- Create website_member_role enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_member_role') THEN
        CREATE TYPE website_member_role AS ENUM ('member', 'editor');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.website_members (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL,
    portal_user_id UUID NOT NULL,
    role website_member_role NOT NULL DEFAULT 'member',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_website_members_portal_user_id_website_id ON website.website_members (portal_user_id, website_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_website_members_metadata_gin ON website.website_members USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_website_members_metadata_deleted_at ON website.website_members ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_website_members_metadata_created_at ON website.website_members ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_website_members_metadata_updated_at ON website.website_members ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.website_members_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS website_members_insert_audit ON website.website_members;
CREATE TRIGGER website_members_insert_audit BEFORE INSERT ON website.website_members
    FOR EACH ROW EXECUTE FUNCTION website.website_members_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS website_members_update_audit ON website.website_members;
CREATE TRIGGER website_members_update_audit BEFORE UPDATE ON website.website_members
    FOR EACH ROW EXECUTE FUNCTION website.website_members_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.website_members ADD CONSTRAINT fk_website_members_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
