-- Migration: Create page_blocks table
-- Generated by metaphor-schema

-- Create website_page_block_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_page_block_kind') THEN
        CREATE TYPE website_page_block_kind AS ENUM ('heading', 'rich_text', 'image', 'cta', 'spacer');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.page_blocks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    page_id UUID NOT NULL,
    kind website_page_block_kind NOT NULL,
    position INTEGER NOT NULL,
    payload JSONB NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_page_blocks_page_id_position ON website.page_blocks (page_id, position);

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.page_blocks ADD CONSTRAINT fk_page_blocks_page_id FOREIGN KEY (page_id) REFERENCES website.pages (id) ON DELETE CASCADE;
