-- Migration: Create menu_blocks table
-- Generated by metaphor-schema

-- Create website_menu_block_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_menu_block_kind') THEN
        CREATE TYPE website_menu_block_kind AS ENUM ('link', 'link_group', 'highlight');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.menu_blocks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    menu_id UUID NOT NULL,
    kind website_menu_block_kind NOT NULL,
    position INTEGER NOT NULL,
    payload JSONB NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_menu_blocks_menu_id_position ON website.menu_blocks (menu_id, position);

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.menu_blocks ADD CONSTRAINT fk_menu_blocks_menu_id FOREIGN KEY (menu_id) REFERENCES website.menus (id) ON DELETE CASCADE;
