-- Migration: Create visitors table
-- Generated by metaphor-schema

-- Create website_visitor_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_visitor_kind') THEN
        CREATE TYPE website_visitor_kind AS ENUM ('anonymous', 'identified');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.visitors (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL,
    access_token TEXT NOT NULL,
    kind website_visitor_kind NOT NULL DEFAULT 'anonymous',
    digest TEXT NOT NULL,
    digest_algo TEXT NOT NULL DEFAULT 'hmac-sha256-v1',
    portal_user_id UUID,
    country_code TEXT,
    visit_count INTEGER NOT NULL DEFAULT 0,
    last_connection_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_visitors_access_token ON website.visitors (access_token);

CREATE UNIQUE INDEX IF NOT EXISTS idx_visitors_digest_website_id ON website.visitors (digest, website_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_visitors_metadata_gin ON website.visitors USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_visitors_metadata_deleted_at ON website.visitors ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_visitors_metadata_created_at ON website.visitors ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_visitors_metadata_updated_at ON website.visitors ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.visitors_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS visitors_insert_audit ON website.visitors;
CREATE TRIGGER visitors_insert_audit BEFORE INSERT ON website.visitors
    FOR EACH ROW EXECUTE FUNCTION website.visitors_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS visitors_update_audit ON website.visitors;
CREATE TRIGGER visitors_update_audit BEFORE UPDATE ON website.visitors
    FOR EACH ROW EXECUTE FUNCTION website.visitors_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.visitors ADD CONSTRAINT fk_visitors_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
