-- Migration: Create website_audit_log table
-- Generated by metaphor-schema

-- Create website_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_audit_event') THEN
        CREATE TYPE website_audit_event AS ENUM ('website_created', 'page_created', 'page_updated', 'page_published', 'page_unpublished', 'page_forked', 'generic_deleted_with_fanout', 'page_renamed', 'menu_created', 'menu_updated', 'menu_deleted', 'menu_fanout', 'redirect_created', 'redirect_updated', 'redirect_deleted', 'visitor_merged', 'visitor_gc_swept', 'intake_received', 'intake_refused', 'publish_refused');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.website_audit_log (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event website_audit_event NOT NULL,
    actor UUID,
    subject_type TEXT,
    subject_id UUID,
    detail JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_website_audit_log_event_occurred_at ON website.website_audit_log (event, occurred_at);
