-- Enum types for website module
-- Generated by metaphor-schema

-- Create website_menu_block_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_menu_block_kind') THEN
        CREATE TYPE website_menu_block_kind AS ENUM ('link', 'link_group', 'highlight');
    END IF;
END
$$;

-- Create website_visibility enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_visibility') THEN
        CREATE TYPE website_visibility AS ENUM ('public', 'connected', 'restricted');
    END IF;
END
$$;

-- Create website_page_block_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_page_block_kind') THEN
        CREATE TYPE website_page_block_kind AS ENUM ('heading', 'rich_text', 'image', 'cta', 'spacer');
    END IF;
END
$$;

-- Create website_redirect_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_redirect_type') THEN
        CREATE TYPE website_redirect_type AS ENUM ('moved_301', 'found_302', 'alias_308', 'gone_404');
    END IF;
END
$$;

-- Create website_visitor_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_visitor_kind') THEN
        CREATE TYPE website_visitor_kind AS ENUM ('anonymous', 'identified');
    END IF;
END
$$;

-- Create website_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_audit_event') THEN
        CREATE TYPE website_audit_event AS ENUM ('website_created', 'page_created', 'page_updated', 'page_published', 'page_unpublished', 'page_forked', 'generic_deleted_with_fanout', 'page_renamed', 'menu_created', 'menu_updated', 'menu_deleted', 'menu_fanout', 'redirect_created', 'redirect_updated', 'redirect_deleted', 'visitor_merged', 'visitor_gc_swept', 'intake_received', 'intake_refused', 'publish_refused');
    END IF;
END
$$;

-- Create website_member_role enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_member_role') THEN
        CREATE TYPE website_member_role AS ENUM ('member', 'editor');
    END IF;
END
$$;

