-- Migration: Create contact_messages table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.contact_messages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL,
    name TEXT,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    notified BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_contact_messages_website_id ON website.contact_messages (website_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_contact_messages_metadata_gin ON website.contact_messages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_contact_messages_metadata_deleted_at ON website.contact_messages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_contact_messages_metadata_created_at ON website.contact_messages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_contact_messages_metadata_updated_at ON website.contact_messages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.contact_messages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS contact_messages_insert_audit ON website.contact_messages;
CREATE TRIGGER contact_messages_insert_audit BEFORE INSERT ON website.contact_messages
    FOR EACH ROW EXECUTE FUNCTION website.contact_messages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS contact_messages_update_audit ON website.contact_messages;
CREATE TRIGGER contact_messages_update_audit BEFORE UPDATE ON website.contact_messages
    FOR EACH ROW EXECUTE FUNCTION website.contact_messages_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.contact_messages ADD CONSTRAINT fk_contact_messages_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
