-- Migration: Create websites table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.websites (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    domain TEXT,
    company_id UUID NOT NULL,
    public_user_id UUID NOT NULL,
    default_lang_code TEXT NOT NULL DEFAULT 'en',
    homepage_url TEXT NOT NULL DEFAULT '/',
    robots_txt TEXT,
    social_links JSONB,
    contact_recipients TEXT[] NOT NULL DEFAULT '{}',
    sequence INTEGER NOT NULL DEFAULT 10,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_websites_company_id_sequence ON website.websites (company_id, sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_websites_metadata_gin ON website.websites USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_websites_metadata_deleted_at ON website.websites ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_websites_metadata_created_at ON website.websites ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_websites_metadata_updated_at ON website.websites ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.websites_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS websites_insert_audit ON website.websites;
CREATE TRIGGER websites_insert_audit BEFORE INSERT ON website.websites
    FOR EACH ROW EXECUTE FUNCTION website.websites_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS websites_update_audit ON website.websites;
CREATE TRIGGER websites_update_audit BEFORE UPDATE ON website.websites
    FOR EACH ROW EXECUTE FUNCTION website.websites_audit_timestamp();
