-- Migration: Create pages table
-- Generated by metaphor-schema

-- Create website_visibility enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'website_visibility') THEN
        CREATE TYPE website_visibility AS ENUM ('public', 'connected', 'restricted');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS website.pages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    key TEXT NOT NULL,
    website_id UUID,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    seo_name TEXT,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    date_publish TIMESTAMPTZ,
    website_indexed BOOLEAN NOT NULL DEFAULT TRUE,
    visibility website_visibility NOT NULL DEFAULT 'public',
    required_member_roles TEXT[] NOT NULL DEFAULT '{}',
    forked_from UUID,
    forked_at TIMESTAMPTZ,
    forked_by UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pages_key ON website.pages (key);

CREATE INDEX IF NOT EXISTS idx_pages_url ON website.pages (url);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pages_metadata_gin ON website.pages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pages_metadata_deleted_at ON website.pages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pages_metadata_created_at ON website.pages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pages_metadata_updated_at ON website.pages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION website.pages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pages_insert_audit ON website.pages;
CREATE TRIGGER pages_insert_audit BEFORE INSERT ON website.pages
    FOR EACH ROW EXECUTE FUNCTION website.pages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pages_update_audit ON website.pages;
CREATE TRIGGER pages_update_audit BEFORE UPDATE ON website.pages
    FOR EACH ROW EXECUTE FUNCTION website.pages_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE website.pages ADD CONSTRAINT fk_pages_website_id FOREIGN KEY (website_id) REFERENCES website.websites (id) ON DELETE CASCADE;
