//! Event handler trait for ContactMessage events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ContactMessageEvent;

/// Event handler for ContactMessage events.
/// Implement this trait to react to ContactMessage lifecycle events.
pub trait ContactMessageEventHandler: EventHandler<ContactMessageEvent> {}
