//! Domain events for ContactMessage entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ContactMessage;

/// Domain events for ContactMessage — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ContactMessage>)` variant.
pub type ContactMessageEvent = CrudEvent<ContactMessage>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ContactMessage events.
pub type ContactMessageEventPublisher = Arc<dyn CrudEventPublisher<ContactMessage> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopContactMessageEventPublisher = NoOpCrudEventPublisher<ContactMessage>;
