//! Domain events for Menu entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Menu;

/// Domain events for Menu — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Menu>)` variant.
pub type MenuEvent = CrudEvent<Menu>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Menu events.
pub type MenuEventPublisher = Arc<dyn CrudEventPublisher<Menu> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMenuEventPublisher = NoOpCrudEventPublisher<Menu>;
