//! Event handler trait for MenuBlock events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MenuBlockEvent;

/// Event handler for MenuBlock events.
/// Implement this trait to react to MenuBlock lifecycle events.
pub trait MenuBlockEventHandler: EventHandler<MenuBlockEvent> {}
