//! Event handler trait for Menu events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MenuEvent;

/// Event handler for Menu events.
/// Implement this trait to react to Menu lifecycle events.
pub trait MenuEventHandler: EventHandler<MenuEvent> {}
