//! Event handler trait for Page events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PageEvent;

/// Event handler for Page events.
/// Implement this trait to react to Page lifecycle events.
pub trait PageEventHandler: EventHandler<PageEvent> {}
