//! Event handler trait for PageBlock events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PageBlockEvent;

/// Event handler for PageBlock events.
/// Implement this trait to react to PageBlock lifecycle events.
pub trait PageBlockEventHandler: EventHandler<PageBlockEvent> {}
