//! Domain events for Page entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Page;

/// Domain events for Page — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Page>)` variant.
pub type PageEvent = CrudEvent<Page>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Page events.
pub type PageEventPublisher = Arc<dyn CrudEventPublisher<Page> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPageEventPublisher = NoOpCrudEventPublisher<Page>;
