//! Domain events for PageBlock entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PageBlock;

/// Domain events for PageBlock — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PageBlock>)` variant.
pub type PageBlockEvent = CrudEvent<PageBlock>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PageBlock events.
pub type PageBlockEventPublisher = Arc<dyn CrudEventPublisher<PageBlock> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPageBlockEventPublisher = NoOpCrudEventPublisher<PageBlock>;
