//! Domain events for Redirect entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Redirect;

/// Domain events for Redirect — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Redirect>)` variant.
pub type RedirectEvent = CrudEvent<Redirect>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Redirect events.
pub type RedirectEventPublisher = Arc<dyn CrudEventPublisher<Redirect> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRedirectEventPublisher = NoOpCrudEventPublisher<Redirect>;
