//! Event handler trait for Redirect events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RedirectEvent;

/// Event handler for Redirect events.
/// Implement this trait to react to Redirect lifecycle events.
pub trait RedirectEventHandler: EventHandler<RedirectEvent> {}
