//! Domain events for Visitor entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Visitor;

/// Domain events for Visitor — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Visitor>)` variant.
pub type VisitorEvent = CrudEvent<Visitor>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Visitor events.
pub type VisitorEventPublisher = Arc<dyn CrudEventPublisher<Visitor> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopVisitorEventPublisher = NoOpCrudEventPublisher<Visitor>;
