//! Event handler trait for VisitorTrack events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::VisitorTrackEvent;

/// Event handler for VisitorTrack events.
/// Implement this trait to react to VisitorTrack lifecycle events.
pub trait VisitorTrackEventHandler: EventHandler<VisitorTrackEvent> {}
