//! Domain events for VisitorTrack entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::VisitorTrack;

/// Domain events for VisitorTrack — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<VisitorTrack>)` variant.
pub type VisitorTrackEvent = CrudEvent<VisitorTrack>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for VisitorTrack events.
pub type VisitorTrackEventPublisher = Arc<dyn CrudEventPublisher<VisitorTrack> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopVisitorTrackEventPublisher = NoOpCrudEventPublisher<VisitorTrack>;
