//! Event handler trait for Website events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WebsiteEvent;

/// Event handler for Website events.
/// Implement this trait to react to Website lifecycle events.
pub trait WebsiteEventHandler: EventHandler<WebsiteEvent> {}
