//! Domain events for WebsiteMember entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WebsiteMember;

/// Domain events for WebsiteMember — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WebsiteMember>)` variant.
pub type WebsiteMemberEvent = CrudEvent<WebsiteMember>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WebsiteMember events.
pub type WebsiteMemberEventPublisher = Arc<dyn CrudEventPublisher<WebsiteMember> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWebsiteMemberEventPublisher = NoOpCrudEventPublisher<WebsiteMember>;
