//! Domain events for Website entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Website;

/// Domain events for Website — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Website>)` variant.
pub type WebsiteEvent = CrudEvent<Website>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Website events.
pub type WebsiteEventPublisher = Arc<dyn CrudEventPublisher<Website> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWebsiteEventPublisher = NoOpCrudEventPublisher<Website>;
