//! Domain events for WebsiteAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WebsiteAuditLog;

/// Domain events for WebsiteAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WebsiteAuditLog>)` variant.
pub type WebsiteAuditLogEvent = CrudEvent<WebsiteAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WebsiteAuditLog events.
pub type WebsiteAuditLogEventPublisher = Arc<dyn CrudEventPublisher<WebsiteAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWebsiteAuditLogEventPublisher = NoOpCrudEventPublisher<WebsiteAuditLog>;
