//! Event handler trait for WebsiteMember events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WebsiteMemberEvent;

/// Event handler for WebsiteMember events.
/// Implement this trait to react to WebsiteMember lifecycle events.
pub trait WebsiteMemberEventHandler: EventHandler<WebsiteMemberEvent> {}
