//! Event handler trait for WebsiteAuditLog events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WebsiteAuditLogEvent;

/// Event handler for WebsiteAuditLog events.
/// Implement this trait to react to WebsiteAuditLog lifecycle events.
pub trait WebsiteAuditLogEventHandler: EventHandler<WebsiteAuditLogEvent> {}
