//! API Versioning
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides API versioning infrastructure:
//! - Version constants and configuration
//! - Version-aware routing
//! - Version negotiation middleware
//! - Backward compatibility helpers

pub mod version;
pub mod version_router;
pub mod version_middleware;
pub mod version_compat;

// Re-exports
pub use version::{ApiVersion, CURRENT_VERSION, SUPPORTED_VERSIONS, VersionParseError};
pub use version_router::{VersionedRouter, versioned_path, versioned_resource_path};
pub use version_middleware::{ResolvedVersion, version_negotiation_middleware};
pub use version_compat::{VersionTransform, VersionedResponse, RenamedField};
