//! Website Integration Layer (Anti-Corruption Layer)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! All external module dependencies must flow through adapters here.
//! The `ModuleAdapter` trait and `IntegrationError` type come from backbone-core.

pub use backbone_core::{ModuleAdapter, ProjectionAdapter, IntegrationError};
pub use backbone_messaging::SubscriberRegistry;

// <<< CUSTOM
// Declare adapter modules for each external dependency. Example:
// pub mod bucket_adapter;
// pub use bucket_adapter::BucketToBersihirAdapter;
// END CUSTOM
