//! ContactMessage seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ContactMessage data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CONTACTMESSAGE SEEDER
// ============================================================================

/// Seeder for contact_message
pub struct SeedContactMessageSeeder;

impl SeedContactMessageSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedContactMessageSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedContactMessageSeeder {
    fn name(&self) -> &'static str {
        "SeedContactMessageSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if website.contact_messages table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM website.contact_messages")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/contact_message_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM website.contact_messages")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

