//! PageBlock seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PageBlock data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PAGEBLOCK SEEDER
// ============================================================================

/// Seeder for page_block
pub struct SeedPageBlockSeeder;

impl SeedPageBlockSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPageBlockSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPageBlockSeeder {
    fn name(&self) -> &'static str {
        "SeedPageBlockSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if website.page_blocks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM website.page_blocks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/page_block_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM website.page_blocks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

