//! Redirect seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Redirect data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// REDIRECT SEEDER
// ============================================================================

/// Seeder for redirect
pub struct SeedRedirectSeeder;

impl SeedRedirectSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRedirectSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRedirectSeeder {
    fn name(&self) -> &'static str {
        "SeedRedirectSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if website.redirects table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM website.redirects")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/redirect_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM website.redirects")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

