//! Visitor seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Visitor data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// VISITOR SEEDER
// ============================================================================

/// Seeder for visitor
pub struct SeedVisitorSeeder;

impl SeedVisitorSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedVisitorSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedVisitorSeeder {
    fn name(&self) -> &'static str {
        "SeedVisitorSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if website.visitors table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM website.visitors")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/visitor_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM website.visitors")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

