//! VisitorTrack seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial VisitorTrack data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// VISITORTRACK SEEDER
// ============================================================================

/// Seeder for visitor_track
pub struct SeedVisitorTrackSeeder;

impl SeedVisitorTrackSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedVisitorTrackSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedVisitorTrackSeeder {
    fn name(&self) -> &'static str {
        "SeedVisitorTrackSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if website.visitor_tracks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM website.visitor_tracks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/visitor_track_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM website.visitor_tracks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

