//! Repository trait for ContactMessage aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ContactMessage aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ContactMessage;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContactMessagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ContactMessagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ContactMessagePaginatedResult {
    pub data: Vec<ContactMessage>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContactMessageFilter {
    pub website_id: Option<Uuid>,
    pub name: Option<String>,
    pub email: Option<String>,
    pub message: Option<String>,
    pub notified: Option<bool>,
}

impl ContactMessageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.name.is_some() || self.email.is_some() || self.message.is_some() || self.notified.is_some()
    }
}

/// Repository trait for ContactMessage aggregate
///
/// This trait defines the persistence contract for ContactMessage entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ContactMessageRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new contact_message entity
    async fn save(&self, entity: &ContactMessage) -> Result<ContactMessage>;

    /// Find contact_message by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ContactMessage>>;

    /// Find all contact_message entities
    async fn find_all(&self) -> Result<Vec<ContactMessage>>;

    /// Update contact_message by ID
    async fn update(&self, id: &str, entity: &ContactMessage) -> Result<Option<ContactMessage>>;

    /// Delete contact_message by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List contact_message with pagination
    async fn list(&self, params: ContactMessagePaginationParams) -> Result<ContactMessagePaginatedResult>;

    /// List contact_message with pagination and filters
    async fn list_with_filters(&self, params: ContactMessagePaginationParams, filters: ContactMessageFilter) -> Result<ContactMessagePaginatedResult>;

    /// Count all contact_message entities
    async fn count(&self) -> Result<u64>;

    /// Count contact_message entities matching filters
    async fn count_with_filters(&self, filters: ContactMessageFilter) -> Result<u64>;

    /// Check if contact_message exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete contact_message by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted contact_message by ID
    async fn restore(&self, id: &str) -> Result<Option<ContactMessage>>;

    /// List soft-deleted contact_message entities
    async fn list_deleted(&self, params: ContactMessagePaginationParams) -> Result<ContactMessagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save contact_message entities
    async fn bulk_save(&self, entities: &[ContactMessage]) -> Result<Vec<ContactMessage>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
