//! Repository trait for MenuBlock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MenuBlock aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MenuBlock, WebsiteMenuBlockKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MenuBlockPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MenuBlockPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MenuBlockPaginatedResult {
    pub data: Vec<MenuBlock>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MenuBlockFilter {
    pub menu_id: Option<Uuid>,
    pub kind: Option<WebsiteMenuBlockKind>,
}

impl MenuBlockFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.menu_id.is_some() || self.kind.is_some()
    }
}

/// Repository trait for MenuBlock aggregate
///
/// This trait defines the persistence contract for MenuBlock entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MenuBlockRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new menu_block entity
    async fn save(&self, entity: &MenuBlock) -> Result<MenuBlock>;

    /// Find menu_block by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MenuBlock>>;

    /// Find all menu_block entities
    async fn find_all(&self) -> Result<Vec<MenuBlock>>;

    /// Update menu_block by ID
    async fn update(&self, id: &str, entity: &MenuBlock) -> Result<Option<MenuBlock>>;

    /// Delete menu_block by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List menu_block with pagination
    async fn list(&self, params: MenuBlockPaginationParams) -> Result<MenuBlockPaginatedResult>;

    /// List menu_block with pagination and filters
    async fn list_with_filters(&self, params: MenuBlockPaginationParams, filters: MenuBlockFilter) -> Result<MenuBlockPaginatedResult>;

    /// Count all menu_block entities
    async fn count(&self) -> Result<u64>;

    /// Count menu_block entities matching filters
    async fn count_with_filters(&self, filters: MenuBlockFilter) -> Result<u64>;

    /// Check if menu_block exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save menu_block entities
    async fn bulk_save(&self, entities: &[MenuBlock]) -> Result<Vec<MenuBlock>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
