//! Repository trait for Menu aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Menu aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Menu, WebsiteVisibility};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MenuPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MenuPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MenuPaginatedResult {
    pub data: Vec<Menu>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MenuFilter {
    pub website_id: Option<Uuid>,
    pub parent_id: Option<Uuid>,
    pub name: Option<String>,
    pub page_id: Option<Uuid>,
    pub url: Option<String>,
    pub new_window: Option<bool>,
    pub visibility: Option<WebsiteVisibility>,
    pub is_mega_menu: Option<bool>,
}

impl MenuFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.parent_id.is_some() || self.name.is_some() || self.page_id.is_some() || self.url.is_some() || self.new_window.is_some() || self.visibility.is_some() || self.is_mega_menu.is_some()
    }
}

/// Repository trait for Menu aggregate
///
/// This trait defines the persistence contract for Menu entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MenuRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new menu entity
    async fn save(&self, entity: &Menu) -> Result<Menu>;

    /// Find menu by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Menu>>;

    /// Find all menu entities
    async fn find_all(&self) -> Result<Vec<Menu>>;

    /// Update menu by ID
    async fn update(&self, id: &str, entity: &Menu) -> Result<Option<Menu>>;

    /// Delete menu by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List menu with pagination
    async fn list(&self, params: MenuPaginationParams) -> Result<MenuPaginatedResult>;

    /// List menu with pagination and filters
    async fn list_with_filters(&self, params: MenuPaginationParams, filters: MenuFilter) -> Result<MenuPaginatedResult>;

    /// Count all menu entities
    async fn count(&self) -> Result<u64>;

    /// Count menu entities matching filters
    async fn count_with_filters(&self, filters: MenuFilter) -> Result<u64>;

    /// Check if menu exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete menu by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted menu by ID
    async fn restore(&self, id: &str) -> Result<Option<Menu>>;

    /// List soft-deleted menu entities
    async fn list_deleted(&self, params: MenuPaginationParams) -> Result<MenuPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save menu entities
    async fn bulk_save(&self, entities: &[Menu]) -> Result<Vec<Menu>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
