//! Repository trait for Page aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Page aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Page, WebsiteVisibility};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PagePaginatedResult {
    pub data: Vec<Page>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PageFilter {
    pub key: Option<String>,
    pub website_id: Option<Uuid>,
    pub url: Option<String>,
    pub title: Option<String>,
    pub seo_name: Option<String>,
    pub is_published: Option<bool>,
    pub website_indexed: Option<bool>,
    pub visibility: Option<WebsiteVisibility>,
    pub forked_from: Option<Uuid>,
    pub forked_by: Option<Uuid>,
}

impl PageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.key.is_some() || self.website_id.is_some() || self.url.is_some() || self.title.is_some() || self.seo_name.is_some() || self.is_published.is_some() || self.website_indexed.is_some() || self.visibility.is_some() || self.forked_from.is_some() || self.forked_by.is_some()
    }
}

/// Repository trait for Page aggregate
///
/// This trait defines the persistence contract for Page entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PageRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new page entity
    async fn save(&self, entity: &Page) -> Result<Page>;

    /// Find page by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Page>>;

    /// Find all page entities
    async fn find_all(&self) -> Result<Vec<Page>>;

    /// Update page by ID
    async fn update(&self, id: &str, entity: &Page) -> Result<Option<Page>>;

    /// Delete page by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List page with pagination
    async fn list(&self, params: PagePaginationParams) -> Result<PagePaginatedResult>;

    /// List page with pagination and filters
    async fn list_with_filters(&self, params: PagePaginationParams, filters: PageFilter) -> Result<PagePaginatedResult>;

    /// Count all page entities
    async fn count(&self) -> Result<u64>;

    /// Count page entities matching filters
    async fn count_with_filters(&self, filters: PageFilter) -> Result<u64>;

    /// Check if page exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete page by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted page by ID
    async fn restore(&self, id: &str) -> Result<Option<Page>>;

    /// List soft-deleted page entities
    async fn list_deleted(&self, params: PagePaginationParams) -> Result<PagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save page entities
    async fn bulk_save(&self, entities: &[Page]) -> Result<Vec<Page>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
