//! Repository trait for PageBlock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PageBlock aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PageBlock, WebsitePageBlockKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PageBlockPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PageBlockPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PageBlockPaginatedResult {
    pub data: Vec<PageBlock>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PageBlockFilter {
    pub page_id: Option<Uuid>,
    pub kind: Option<WebsitePageBlockKind>,
}

impl PageBlockFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.page_id.is_some() || self.kind.is_some()
    }
}

/// Repository trait for PageBlock aggregate
///
/// This trait defines the persistence contract for PageBlock entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PageBlockRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new page_block entity
    async fn save(&self, entity: &PageBlock) -> Result<PageBlock>;

    /// Find page_block by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PageBlock>>;

    /// Find all page_block entities
    async fn find_all(&self) -> Result<Vec<PageBlock>>;

    /// Update page_block by ID
    async fn update(&self, id: &str, entity: &PageBlock) -> Result<Option<PageBlock>>;

    /// Delete page_block by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List page_block with pagination
    async fn list(&self, params: PageBlockPaginationParams) -> Result<PageBlockPaginatedResult>;

    /// List page_block with pagination and filters
    async fn list_with_filters(&self, params: PageBlockPaginationParams, filters: PageBlockFilter) -> Result<PageBlockPaginatedResult>;

    /// Count all page_block entities
    async fn count(&self) -> Result<u64>;

    /// Count page_block entities matching filters
    async fn count_with_filters(&self, filters: PageBlockFilter) -> Result<u64>;

    /// Check if page_block exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save page_block entities
    async fn bulk_save(&self, entities: &[PageBlock]) -> Result<Vec<PageBlock>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
