//! Repository trait for Redirect aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Redirect aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Redirect, WebsiteRedirectType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RedirectPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RedirectPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RedirectPaginatedResult {
    pub data: Vec<Redirect>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RedirectFilter {
    pub website_id: Option<Uuid>,
    pub url_from: Option<String>,
    pub redirect_type: Option<WebsiteRedirectType>,
    pub url_to: Option<String>,
    pub description: Option<String>,
}

impl RedirectFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.url_from.is_some() || self.redirect_type.is_some() || self.url_to.is_some() || self.description.is_some()
    }
}

/// Repository trait for Redirect aggregate
///
/// This trait defines the persistence contract for Redirect entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RedirectRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new redirect entity
    async fn save(&self, entity: &Redirect) -> Result<Redirect>;

    /// Find redirect by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Redirect>>;

    /// Find all redirect entities
    async fn find_all(&self) -> Result<Vec<Redirect>>;

    /// Update redirect by ID
    async fn update(&self, id: &str, entity: &Redirect) -> Result<Option<Redirect>>;

    /// Delete redirect by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List redirect with pagination
    async fn list(&self, params: RedirectPaginationParams) -> Result<RedirectPaginatedResult>;

    /// List redirect with pagination and filters
    async fn list_with_filters(&self, params: RedirectPaginationParams, filters: RedirectFilter) -> Result<RedirectPaginatedResult>;

    /// Count all redirect entities
    async fn count(&self) -> Result<u64>;

    /// Count redirect entities matching filters
    async fn count_with_filters(&self, filters: RedirectFilter) -> Result<u64>;

    /// Check if redirect exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete redirect by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted redirect by ID
    async fn restore(&self, id: &str) -> Result<Option<Redirect>>;

    /// List soft-deleted redirect entities
    async fn list_deleted(&self, params: RedirectPaginationParams) -> Result<RedirectPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save redirect entities
    async fn bulk_save(&self, entities: &[Redirect]) -> Result<Vec<Redirect>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
