//! Repository trait for VisitorTrack aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the VisitorTrack aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::VisitorTrack;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct VisitorTrackPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl VisitorTrackPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct VisitorTrackPaginatedResult {
    pub data: Vec<VisitorTrack>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct VisitorTrackFilter {
    pub visitor_id: Option<Uuid>,
    pub page_id: Option<Uuid>,
    pub url: Option<String>,
}

impl VisitorTrackFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.visitor_id.is_some() || self.page_id.is_some() || self.url.is_some()
    }
}

/// Repository trait for VisitorTrack aggregate
///
/// This trait defines the persistence contract for VisitorTrack entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait VisitorTrackRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new visitor_track entity
    async fn save(&self, entity: &VisitorTrack) -> Result<VisitorTrack>;

    /// Find visitor_track by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<VisitorTrack>>;

    /// Find all visitor_track entities
    async fn find_all(&self) -> Result<Vec<VisitorTrack>>;

    /// Update visitor_track by ID
    async fn update(&self, id: &str, entity: &VisitorTrack) -> Result<Option<VisitorTrack>>;

    /// Delete visitor_track by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List visitor_track with pagination
    async fn list(&self, params: VisitorTrackPaginationParams) -> Result<VisitorTrackPaginatedResult>;

    /// List visitor_track with pagination and filters
    async fn list_with_filters(&self, params: VisitorTrackPaginationParams, filters: VisitorTrackFilter) -> Result<VisitorTrackPaginatedResult>;

    /// Count all visitor_track entities
    async fn count(&self) -> Result<u64>;

    /// Count visitor_track entities matching filters
    async fn count_with_filters(&self, filters: VisitorTrackFilter) -> Result<u64>;

    /// Check if visitor_track exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save visitor_track entities
    async fn bulk_save(&self, entities: &[VisitorTrack]) -> Result<Vec<VisitorTrack>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
