//! Repository trait for Visitor aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Visitor aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Visitor, WebsiteVisitorKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct VisitorPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl VisitorPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct VisitorPaginatedResult {
    pub data: Vec<Visitor>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct VisitorFilter {
    pub website_id: Option<Uuid>,
    pub access_token: Option<String>,
    pub kind: Option<WebsiteVisitorKind>,
    pub digest: Option<String>,
    pub digest_algo: Option<String>,
    pub portal_user_id: Option<Uuid>,
    pub country_code: Option<String>,
}

impl VisitorFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.access_token.is_some() || self.kind.is_some() || self.digest.is_some() || self.digest_algo.is_some() || self.portal_user_id.is_some() || self.country_code.is_some()
    }
}

/// Repository trait for Visitor aggregate
///
/// This trait defines the persistence contract for Visitor entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait VisitorRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new visitor entity
    async fn save(&self, entity: &Visitor) -> Result<Visitor>;

    /// Find visitor by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Visitor>>;

    /// Find all visitor entities
    async fn find_all(&self) -> Result<Vec<Visitor>>;

    /// Update visitor by ID
    async fn update(&self, id: &str, entity: &Visitor) -> Result<Option<Visitor>>;

    /// Delete visitor by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List visitor with pagination
    async fn list(&self, params: VisitorPaginationParams) -> Result<VisitorPaginatedResult>;

    /// List visitor with pagination and filters
    async fn list_with_filters(&self, params: VisitorPaginationParams, filters: VisitorFilter) -> Result<VisitorPaginatedResult>;

    /// Count all visitor entities
    async fn count(&self) -> Result<u64>;

    /// Count visitor entities matching filters
    async fn count_with_filters(&self, filters: VisitorFilter) -> Result<u64>;

    /// Check if visitor exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete visitor by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted visitor by ID
    async fn restore(&self, id: &str) -> Result<Option<Visitor>>;

    /// List soft-deleted visitor entities
    async fn list_deleted(&self, params: VisitorPaginationParams) -> Result<VisitorPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save visitor entities
    async fn bulk_save(&self, entities: &[Visitor]) -> Result<Vec<Visitor>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
