//! Repository trait for Website aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Website aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Website;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsitePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WebsitePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WebsitePaginatedResult {
    pub data: Vec<Website>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteFilter {
    pub name: Option<String>,
    pub domain: Option<String>,
    pub company_id: Option<Uuid>,
    pub public_user_id: Option<Uuid>,
    pub default_lang_code: Option<String>,
    pub homepage_url: Option<String>,
    pub robots_txt: Option<String>,
}

impl WebsiteFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.domain.is_some() || self.company_id.is_some() || self.public_user_id.is_some() || self.default_lang_code.is_some() || self.homepage_url.is_some() || self.robots_txt.is_some()
    }
}

/// Repository trait for Website aggregate
///
/// This trait defines the persistence contract for Website entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WebsiteRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new website entity
    async fn save(&self, entity: &Website) -> Result<Website>;

    /// Find website by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Website>>;

    /// Find all website entities
    async fn find_all(&self) -> Result<Vec<Website>>;

    /// Update website by ID
    async fn update(&self, id: &str, entity: &Website) -> Result<Option<Website>>;

    /// Delete website by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List website with pagination
    async fn list(&self, params: WebsitePaginationParams) -> Result<WebsitePaginatedResult>;

    /// List website with pagination and filters
    async fn list_with_filters(&self, params: WebsitePaginationParams, filters: WebsiteFilter) -> Result<WebsitePaginatedResult>;

    /// Count all website entities
    async fn count(&self) -> Result<u64>;

    /// Count website entities matching filters
    async fn count_with_filters(&self, filters: WebsiteFilter) -> Result<u64>;

    /// Check if website exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete website by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted website by ID
    async fn restore(&self, id: &str) -> Result<Option<Website>>;

    /// List soft-deleted website entities
    async fn list_deleted(&self, params: WebsitePaginationParams) -> Result<WebsitePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save website entities
    async fn bulk_save(&self, entities: &[Website]) -> Result<Vec<Website>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
