//! Repository trait for WebsiteAuditLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WebsiteAuditLog aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{WebsiteAuditLog, WebsiteAuditEvent};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteAuditLogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WebsiteAuditLogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WebsiteAuditLogPaginatedResult {
    pub data: Vec<WebsiteAuditLog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteAuditLogFilter {
    pub event: Option<WebsiteAuditEvent>,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
}

impl WebsiteAuditLogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event.is_some() || self.actor.is_some() || self.subject_type.is_some() || self.subject_id.is_some()
    }
}

/// Repository trait for WebsiteAuditLog aggregate
///
/// This trait defines the persistence contract for WebsiteAuditLog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WebsiteAuditLogRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new website_audit_log entity
    async fn save(&self, entity: &WebsiteAuditLog) -> Result<WebsiteAuditLog>;

    /// Find website_audit_log by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WebsiteAuditLog>>;

    /// Find all website_audit_log entities
    async fn find_all(&self) -> Result<Vec<WebsiteAuditLog>>;

    /// Update website_audit_log by ID
    async fn update(&self, id: &str, entity: &WebsiteAuditLog) -> Result<Option<WebsiteAuditLog>>;

    /// Delete website_audit_log by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List website_audit_log with pagination
    async fn list(&self, params: WebsiteAuditLogPaginationParams) -> Result<WebsiteAuditLogPaginatedResult>;

    /// List website_audit_log with pagination and filters
    async fn list_with_filters(&self, params: WebsiteAuditLogPaginationParams, filters: WebsiteAuditLogFilter) -> Result<WebsiteAuditLogPaginatedResult>;

    /// Count all website_audit_log entities
    async fn count(&self) -> Result<u64>;

    /// Count website_audit_log entities matching filters
    async fn count_with_filters(&self, filters: WebsiteAuditLogFilter) -> Result<u64>;

    /// Check if website_audit_log exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save website_audit_log entities
    async fn bulk_save(&self, entities: &[WebsiteAuditLog]) -> Result<Vec<WebsiteAuditLog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
