//! Repository trait for WebsiteMember aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WebsiteMember aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{WebsiteMember, WebsiteMemberRole};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteMemberPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WebsiteMemberPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WebsiteMemberPaginatedResult {
    pub data: Vec<WebsiteMember>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteMemberFilter {
    pub website_id: Option<Uuid>,
    pub portal_user_id: Option<Uuid>,
    pub role: Option<WebsiteMemberRole>,
}

impl WebsiteMemberFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.portal_user_id.is_some() || self.role.is_some()
    }
}

/// Repository trait for WebsiteMember aggregate
///
/// This trait defines the persistence contract for WebsiteMember entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WebsiteMemberRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new website_member entity
    async fn save(&self, entity: &WebsiteMember) -> Result<WebsiteMember>;

    /// Find website_member by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WebsiteMember>>;

    /// Find all website_member entities
    async fn find_all(&self) -> Result<Vec<WebsiteMember>>;

    /// Update website_member by ID
    async fn update(&self, id: &str, entity: &WebsiteMember) -> Result<Option<WebsiteMember>>;

    /// Delete website_member by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List website_member with pagination
    async fn list(&self, params: WebsiteMemberPaginationParams) -> Result<WebsiteMemberPaginatedResult>;

    /// List website_member with pagination and filters
    async fn list_with_filters(&self, params: WebsiteMemberPaginationParams, filters: WebsiteMemberFilter) -> Result<WebsiteMemberPaginatedResult>;

    /// Count all website_member entities
    async fn count(&self) -> Result<u64>;

    /// Count website_member entities matching filters
    async fn count_with_filters(&self, filters: WebsiteMemberFilter) -> Result<u64>;

    /// Check if website_member exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete website_member by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted website_member by ID
    async fn restore(&self, id: &str) -> Result<Option<WebsiteMember>>;

    /// List soft-deleted website_member entities
    async fn list_deleted(&self, params: WebsiteMemberPaginationParams) -> Result<WebsiteMemberPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save website_member entities
    async fn bulk_save(&self, entities: &[WebsiteMember]) -> Result<Vec<WebsiteMember>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
