//! Repository for Menu entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Menu, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Menu;

/// Table name for Menu entities
pub const TABLE_NAME: &str = "website.menus";

/// Repository for Menu entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MenuRepository(
    backbone_orm::GenericCrudRepository<Menu, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MenuRepository {
    type Target = backbone_orm::GenericCrudRepository<Menu, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MenuRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MenuRepository, Menu, soft_delete);
