//! Repository for MenuBlock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MenuBlock, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MenuBlock;

/// Table name for MenuBlock entities
pub const TABLE_NAME: &str = "website.menu_blocks";

/// Repository for MenuBlock entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MenuBlockRepository(
    backbone_orm::GenericCrudRepository<MenuBlock, backbone_orm::HardDelete>,
);

impl std::ops::Deref for MenuBlockRepository {
    type Target = backbone_orm::GenericCrudRepository<MenuBlock, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MenuBlockRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MenuBlockRepository, MenuBlock, no_soft_delete);
