//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod contact_message_repository;
mod menu_repository;
mod menu_block_repository;
mod page_repository;
mod page_block_repository;
mod redirect_repository;
mod visitor_repository;
mod visitor_track_repository;
mod website_repository;
mod website_member_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use contact_message_repository::ContactMessageRepository;
pub use menu_repository::MenuRepository;
pub use menu_block_repository::MenuBlockRepository;
pub use page_repository::PageRepository;
pub use page_block_repository::PageBlockRepository;
pub use redirect_repository::RedirectRepository;
pub use visitor_repository::VisitorRepository;
pub use visitor_track_repository::VisitorTrackRepository;
pub use website_repository::WebsiteRepository;
pub use website_member_repository::WebsiteMemberRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
/// Bind the ambient organization scope onto a connection this module opened
/// itself. Every write transaction the module owns calls this right after
/// `begin`, so the org fence (once the composition declares this schema
/// scoped) sees the caller's entitlements instead of refusing the write at
/// the kind guard. A no-op while no ambient scope exists (seeder and
/// officer-tool paths), which keeps the module correct before the fence
/// lands.
pub(crate) async fn relay_ambient_scope(
    conn: &mut sqlx::PgConnection,
) -> Result<(), sqlx::Error> {
    if let Some(scope) = backbone_orm::org_scope::current_org_scope() {
        backbone_orm::org_scope::bind_org_scope_on(conn, &scope).await?;
    }
    Ok(())
}
// END CUSTOM
