//! Repository for PageBlock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PageBlock, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PageBlock;

/// Table name for PageBlock entities
pub const TABLE_NAME: &str = "website.page_blocks";

/// Repository for PageBlock entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PageBlockRepository(
    backbone_orm::GenericCrudRepository<PageBlock, backbone_orm::HardDelete>,
);

impl std::ops::Deref for PageBlockRepository {
    type Target = backbone_orm::GenericCrudRepository<PageBlock, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PageBlockRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PageBlockRepository, PageBlock, no_soft_delete);
