//! Repository for Page entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Page, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Page;

/// Table name for Page entities
pub const TABLE_NAME: &str = "website.pages";

/// Repository for Page entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PageRepository(
    backbone_orm::GenericCrudRepository<Page, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PageRepository {
    type Target = backbone_orm::GenericCrudRepository<Page, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PageRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PageRepository, Page, soft_delete);
