//! Repository for Redirect entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Redirect, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Redirect;

/// Table name for Redirect entities
pub const TABLE_NAME: &str = "website.redirects";

/// Repository for Redirect entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RedirectRepository(
    backbone_orm::GenericCrudRepository<Redirect, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RedirectRepository {
    type Target = backbone_orm::GenericCrudRepository<Redirect, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RedirectRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RedirectRepository, Redirect, soft_delete);
