//! Repository for VisitorTrack entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<VisitorTrack, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::VisitorTrack;

/// Table name for VisitorTrack entities
pub const TABLE_NAME: &str = "website.visitor_tracks";

/// Repository for VisitorTrack entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct VisitorTrackRepository(
    backbone_orm::GenericCrudRepository<VisitorTrack, backbone_orm::HardDelete>,
);

impl std::ops::Deref for VisitorTrackRepository {
    type Target = backbone_orm::GenericCrudRepository<VisitorTrack, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl VisitorTrackRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(VisitorTrackRepository, VisitorTrack, no_soft_delete);
