//! Repository for WebsiteMember entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WebsiteMember, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WebsiteMember;

/// Table name for WebsiteMember entities
pub const TABLE_NAME: &str = "website.website_members";

/// Repository for WebsiteMember entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WebsiteMemberRepository(
    backbone_orm::GenericCrudRepository<WebsiteMember, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WebsiteMemberRepository {
    type Target = backbone_orm::GenericCrudRepository<WebsiteMember, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WebsiteMemberRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WebsiteMemberRepository, WebsiteMember, soft_delete);
