//! Repository for WebsiteAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WebsiteAuditLog, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WebsiteAuditLog;

/// Table name for WebsiteAuditLog entities
pub const TABLE_NAME: &str = "website.website_audit_log";

/// Repository for WebsiteAuditLog entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WebsiteAuditLogRepository(
    backbone_orm::GenericCrudRepository<WebsiteAuditLog, backbone_orm::HardDelete>,
);

impl std::ops::Deref for WebsiteAuditLogRepository {
    type Target = backbone_orm::GenericCrudRepository<WebsiteAuditLog, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WebsiteAuditLogRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WebsiteAuditLogRepository, WebsiteAuditLog, no_soft_delete);
