//! Validator for ContactMessage entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ContactMessage>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ContactMessage;

/// Validator type alias for ContactMessage entities.
pub type ContactMessageValidator = EntityValidator<ContactMessage>;

/// Build a validator for ContactMessage with all schema-defined field rules.
pub fn contact_message_validator() -> ContactMessageValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("name", |e: &ContactMessage| e.name.as_deref()))
        .rule(RequiredString::new("email", |e: &ContactMessage| &e.email))
        .rule(RequiredString::new("message", |e: &ContactMessage| &e.message))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
