//! Validator for Menu entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Menu>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Menu;

/// Validator type alias for Menu entities.
pub type MenuValidator = EntityValidator<Menu>;

/// Build a validator for Menu with all schema-defined field rules.
pub fn menu_validator() -> MenuValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Menu| &e.name))
        .rule(OptionalNotBlank::new("url", |e: &Menu| e.url.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
