//! Validator for MenuBlock entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MenuBlock>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::MenuBlock;

/// Validator type alias for MenuBlock entities.
pub type MenuBlockValidator = EntityValidator<MenuBlock>;

/// Build a validator for MenuBlock with all schema-defined field rules.
pub fn menu_block_validator() -> MenuBlockValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
