//! Validator for PageBlock entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PageBlock>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::PageBlock;

/// Validator type alias for PageBlock entities.
pub type PageBlockValidator = EntityValidator<PageBlock>;

/// Build a validator for PageBlock with all schema-defined field rules.
pub fn page_block_validator() -> PageBlockValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
