//! Validator for Redirect entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Redirect>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Redirect;

/// Validator type alias for Redirect entities.
pub type RedirectValidator = EntityValidator<Redirect>;

/// Build a validator for Redirect with all schema-defined field rules.
pub fn redirect_validator() -> RedirectValidator {
    EntityValidator::new()
        .rule(RequiredString::new("url_from", |e: &Redirect| &e.url_from))
        .rule(OptionalNotBlank::new("url_to", |e: &Redirect| e.url_to.as_deref()))
        .rule(OptionalNotBlank::new("description", |e: &Redirect| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
