//! Shared validation types — re-exported from backbone-core.
//!
//! Generated by metaphor-schema. Do not edit manually.

pub use backbone_core::{
    ValidationError, ValidationErrors, EntityValidator,
    RequiredString, MaxLength, NonNegative, OptionalNotBlank, Regex, RequiredUuid,
};

/// Convenience result type for validation.
pub type ValidationResult = Result<(), ValidationErrors>;
