//! Validator for Visitor entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Visitor>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Visitor;

/// Validator type alias for Visitor entities.
pub type VisitorValidator = EntityValidator<Visitor>;

/// Build a validator for Visitor with all schema-defined field rules.
pub fn visitor_validator() -> VisitorValidator {
    EntityValidator::new()
        .rule(RequiredString::new("access_token", |e: &Visitor| &e.access_token))
        .rule(RequiredString::new("digest", |e: &Visitor| &e.digest))
        .rule(RequiredString::new("digest_algo", |e: &Visitor| &e.digest_algo))
        .rule(OptionalNotBlank::new("country_code", |e: &Visitor| e.country_code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
