//! Validator for VisitorTrack entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<VisitorTrack>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::VisitorTrack;

/// Validator type alias for VisitorTrack entities.
pub type VisitorTrackValidator = EntityValidator<VisitorTrack>;

/// Build a validator for VisitorTrack with all schema-defined field rules.
pub fn visitor_track_validator() -> VisitorTrackValidator {
    EntityValidator::new()
        .rule(RequiredString::new("url", |e: &VisitorTrack| &e.url))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
