//! Validator for WebsiteMember entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WebsiteMember>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::WebsiteMember;

/// Validator type alias for WebsiteMember entities.
pub type WebsiteMemberValidator = EntityValidator<WebsiteMember>;

/// Build a validator for WebsiteMember with all schema-defined field rules.
pub fn website_member_validator() -> WebsiteMemberValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
