//! Validator for Website entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Website>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Website;

/// Validator type alias for Website entities.
pub type WebsiteValidator = EntityValidator<Website>;

/// Build a validator for Website with all schema-defined field rules.
pub fn website_validator() -> WebsiteValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Website| &e.name))
        .rule(OptionalNotBlank::new("domain", |e: &Website| e.domain.as_deref()))
        .rule(RequiredString::new("default_lang_code", |e: &Website| &e.default_lang_code))
        .rule(RequiredString::new("homepage_url", |e: &Website| &e.homepage_url))
        .rule(OptionalNotBlank::new("robots_txt", |e: &Website| e.robots_txt.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
