//! Validator for WebsiteAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WebsiteAuditLog>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::WebsiteAuditLog;

/// Validator type alias for WebsiteAuditLog entities.
pub type WebsiteAuditLogValidator = EntityValidator<WebsiteAuditLog>;

/// Build a validator for WebsiteAuditLog with all schema-defined field rules.
pub fn website_audit_log_validator() -> WebsiteAuditLogValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("subject_type", |e: &WebsiteAuditLog| e.subject_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
