//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod contact_message;
pub mod menu;
pub mod menu_block;
pub mod page;
pub mod page_block;
pub mod redirect;
pub mod visitor;
pub mod visitor_track;
pub mod website;
pub mod website_audit_log;
pub mod website_member;
pub mod website_menu_block_kind;
pub mod website_visibility;
pub mod website_page_block_kind;
pub mod website_redirect_type;
pub mod website_visitor_kind;
pub mod website_audit_event;
pub mod website_member_role;

// Re-exports
pub use contact_message::ContactMessage;
pub use contact_message::ContactMessageBuilder;
pub use contact_message::ContactMessageId;
pub use menu::Menu;
pub use menu::MenuBuilder;
pub use menu::MenuId;
pub use menu_block::MenuBlock;
pub use menu_block::MenuBlockBuilder;
pub use menu_block::MenuBlockId;
pub use page::Page;
pub use page::PageBuilder;
pub use page::PageId;
pub use page_block::PageBlock;
pub use page_block::PageBlockBuilder;
pub use page_block::PageBlockId;
pub use redirect::Redirect;
pub use redirect::RedirectBuilder;
pub use redirect::RedirectId;
pub use visitor::Visitor;
pub use visitor::VisitorBuilder;
pub use visitor::VisitorId;
pub use visitor_track::VisitorTrack;
pub use visitor_track::VisitorTrackBuilder;
pub use visitor_track::VisitorTrackId;
pub use website::Website;
pub use website::WebsiteBuilder;
pub use website::WebsiteId;
pub use website_audit_log::WebsiteAuditLog;
pub use website_audit_log::WebsiteAuditLogBuilder;
pub use website_audit_log::WebsiteAuditLogId;
pub use website_member::WebsiteMember;
pub use website_member::WebsiteMemberBuilder;
pub use website_member::WebsiteMemberId;
pub use website_menu_block_kind::WebsiteMenuBlockKind;
pub use website_visibility::WebsiteVisibility;
pub use website_page_block_kind::WebsitePageBlockKind;
pub use website_redirect_type::WebsiteRedirectType;
pub use website_visitor_kind::WebsiteVisitorKind;
pub use website_audit_event::WebsiteAuditEvent;
pub use website_member_role::WebsiteMemberRole;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
