//! Website Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ContactMessageService;
use crate::application::service::MenuService;
use crate::application::service::MenuBlockService;
use crate::application::service::PageService;
use crate::application::service::PageBlockService;
use crate::application::service::RedirectService;
use crate::application::service::VisitorService;
use crate::application::service::VisitorTrackService;
use crate::application::service::WebsiteService;
use crate::application::service::WebsiteAuditLogService;
use crate::application::service::WebsiteMemberService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ContactMessage service
    pub contact_message_service: Arc<ContactMessageService>,
    /// Menu service
    pub menu_service: Arc<MenuService>,
    /// MenuBlock service
    pub menu_block_service: Arc<MenuBlockService>,
    /// Page service
    pub page_service: Arc<PageService>,
    /// PageBlock service
    pub page_block_service: Arc<PageBlockService>,
    /// Redirect service
    pub redirect_service: Arc<RedirectService>,
    /// Visitor service
    pub visitor_service: Arc<VisitorService>,
    /// VisitorTrack service
    pub visitor_track_service: Arc<VisitorTrackService>,
    /// Website service
    pub website_service: Arc<WebsiteService>,
    /// WebsiteAuditLog service
    pub website_audit_log_service: Arc<WebsiteAuditLogService>,
    /// WebsiteMember service
    pub website_member_service: Arc<WebsiteMemberService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        contact_message_service: Arc<ContactMessageService>,
        menu_service: Arc<MenuService>,
        menu_block_service: Arc<MenuBlockService>,
        page_service: Arc<PageService>,
        page_block_service: Arc<PageBlockService>,
        redirect_service: Arc<RedirectService>,
        visitor_service: Arc<VisitorService>,
        visitor_track_service: Arc<VisitorTrackService>,
        website_service: Arc<WebsiteService>,
        website_audit_log_service: Arc<WebsiteAuditLogService>,
        website_member_service: Arc<WebsiteMemberService>
    ) -> Self {
        Self {
            contact_message_service,
            menu_service,
            menu_block_service,
            page_service,
            page_block_service,
            redirect_service,
            visitor_service,
            visitor_track_service,
            website_service,
            website_audit_log_service,
            website_member_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::WebsiteModule) -> Self {
        Self {
            contact_message_service: module.contact_message_service.clone(),
            menu_service: module.menu_service.clone(),
            menu_block_service: module.menu_block_service.clone(),
            page_service: module.page_service.clone(),
            page_block_service: module.page_block_service.clone(),
            redirect_service: module.redirect_service.clone(),
            visitor_service: module.visitor_service.clone(),
            visitor_track_service: module.visitor_track_service.clone(),
            website_service: module.website_service.clone(),
            website_audit_log_service: module.website_audit_log_service.clone(),
            website_member_service: module.website_member_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    contact_message_service: Option<Arc<ContactMessageService>>,
    menu_service: Option<Arc<MenuService>>,
    menu_block_service: Option<Arc<MenuBlockService>>,
    page_service: Option<Arc<PageService>>,
    page_block_service: Option<Arc<PageBlockService>>,
    redirect_service: Option<Arc<RedirectService>>,
    visitor_service: Option<Arc<VisitorService>>,
    visitor_track_service: Option<Arc<VisitorTrackService>>,
    website_service: Option<Arc<WebsiteService>>,
    website_audit_log_service: Option<Arc<WebsiteAuditLogService>>,
    website_member_service: Option<Arc<WebsiteMemberService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ContactMessage service.
    pub fn with_contact_message_service(mut self, service: Arc<ContactMessageService>) -> Self {
        self.contact_message_service = Some(service);
        self
    }

    /// Set the Menu service.
    pub fn with_menu_service(mut self, service: Arc<MenuService>) -> Self {
        self.menu_service = Some(service);
        self
    }

    /// Set the MenuBlock service.
    pub fn with_menu_block_service(mut self, service: Arc<MenuBlockService>) -> Self {
        self.menu_block_service = Some(service);
        self
    }

    /// Set the Page service.
    pub fn with_page_service(mut self, service: Arc<PageService>) -> Self {
        self.page_service = Some(service);
        self
    }

    /// Set the PageBlock service.
    pub fn with_page_block_service(mut self, service: Arc<PageBlockService>) -> Self {
        self.page_block_service = Some(service);
        self
    }

    /// Set the Redirect service.
    pub fn with_redirect_service(mut self, service: Arc<RedirectService>) -> Self {
        self.redirect_service = Some(service);
        self
    }

    /// Set the Visitor service.
    pub fn with_visitor_service(mut self, service: Arc<VisitorService>) -> Self {
        self.visitor_service = Some(service);
        self
    }

    /// Set the VisitorTrack service.
    pub fn with_visitor_track_service(mut self, service: Arc<VisitorTrackService>) -> Self {
        self.visitor_track_service = Some(service);
        self
    }

    /// Set the Website service.
    pub fn with_website_service(mut self, service: Arc<WebsiteService>) -> Self {
        self.website_service = Some(service);
        self
    }

    /// Set the WebsiteAuditLog service.
    pub fn with_website_audit_log_service(mut self, service: Arc<WebsiteAuditLogService>) -> Self {
        self.website_audit_log_service = Some(service);
        self
    }

    /// Set the WebsiteMember service.
    pub fn with_website_member_service(mut self, service: Arc<WebsiteMemberService>) -> Self {
        self.website_member_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            contact_message_service: self.contact_message_service.expect("contact_message_service is required"),
            menu_service: self.menu_service.expect("menu_service is required"),
            menu_block_service: self.menu_block_service.expect("menu_block_service is required"),
            page_service: self.page_service.expect("page_service is required"),
            page_block_service: self.page_block_service.expect("page_block_service is required"),
            redirect_service: self.redirect_service.expect("redirect_service is required"),
            visitor_service: self.visitor_service.expect("visitor_service is required"),
            visitor_track_service: self.visitor_track_service.expect("visitor_track_service is required"),
            website_service: self.website_service.expect("website_service is required"),
            website_audit_log_service: self.website_audit_log_service.expect("website_audit_log_service is required"),
            website_member_service: self.website_member_service.expect("website_member_service is required"),
        }
    }
}
