//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    contact_message_handler::create_contact_message_read_routes,
    menu_handler::create_menu_read_routes,
    menu_block_handler::create_menu_block_read_routes,
    page_handler::create_page_read_routes,
    page_block_handler::create_page_block_read_routes,
    redirect_handler::create_redirect_read_routes,
    visitor_handler::create_visitor_read_routes,
    visitor_track_handler::create_visitor_track_read_routes,
    website_handler::create_website_read_routes,
    website_audit_log_handler::create_website_audit_log_read_routes,
    website_member_handler::create_website_member_read_routes,
};

use crate::application::service::{
    ContactMessageService,
    MenuService,
    MenuBlockService,
    PageService,
    PageBlockService,
    RedirectService,
    VisitorService,
    VisitorTrackService,
    WebsiteService,
    WebsiteAuditLogService,
    WebsiteMemberService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub contact_message: Arc<ContactMessageService>,
    pub menu: Arc<MenuService>,
    pub menu_block: Arc<MenuBlockService>,
    pub page: Arc<PageService>,
    pub page_block: Arc<PageBlockService>,
    pub redirect: Arc<RedirectService>,
    pub visitor: Arc<VisitorService>,
    pub visitor_track: Arc<VisitorTrackService>,
    pub website: Arc<WebsiteService>,
    pub website_audit_log: Arc<WebsiteAuditLogService>,
    pub website_member: Arc<WebsiteMemberService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // ContactMessage routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_contact_message_read_routes(services.contact_message))
        // Menu routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_menu_read_routes(services.menu))
        // MenuBlock routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_menu_block_read_routes(services.menu_block))
        // Page routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_page_read_routes(services.page))
        // PageBlock routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_page_block_read_routes(services.page_block))
        // Redirect routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_redirect_read_routes(services.redirect))
        // Visitor routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_visitor_read_routes(services.visitor))
        // VisitorTrack routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_visitor_track_read_routes(services.visitor_track))
        // Website routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_website_read_routes(services.website))
        // WebsiteAuditLog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_website_audit_log_read_routes(services.website_audit_log))
        // WebsiteMember routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_website_member_read_routes(services.website_member))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn contact_message_routes(service: Arc<ContactMessageService>) -> Router {
        create_contact_message_routes(service)
    }

    pub fn menu_routes(service: Arc<MenuService>) -> Router {
        create_menu_routes(service)
    }

    pub fn menu_block_routes(service: Arc<MenuBlockService>) -> Router {
        create_menu_block_routes(service)
    }

    pub fn page_routes(service: Arc<PageService>) -> Router {
        create_page_routes(service)
    }

    pub fn page_block_routes(service: Arc<PageBlockService>) -> Router {
        create_page_block_routes(service)
    }

    pub fn redirect_routes(service: Arc<RedirectService>) -> Router {
        create_redirect_routes(service)
    }

    pub fn visitor_routes(service: Arc<VisitorService>) -> Router {
        create_visitor_routes(service)
    }

    pub fn visitor_track_routes(service: Arc<VisitorTrackService>) -> Router {
        create_visitor_track_routes(service)
    }

    pub fn website_routes(service: Arc<WebsiteService>) -> Router {
        create_website_routes(service)
    }

    pub fn website_audit_log_routes(service: Arc<WebsiteAuditLogService>) -> Router {
        create_website_audit_log_routes(service)
    }

    pub fn website_member_routes(service: Arc<WebsiteMemberService>) -> Router {
        create_website_member_routes(service)
    }

}
