//! Public events for Website module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CONTACTMESSAGE EVENTS
// ============================================================================

/// Event published when a ContactMessage is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageCreatedEvent {
    pub id: ContactMessageId,
    pub data: ContactMessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ContactMessage is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageUpdatedEvent {
    pub id: ContactMessageId,
    pub data: ContactMessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ContactMessage is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageDeletedEvent {
    pub id: ContactMessageId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MENU EVENTS
// ============================================================================

/// Event published when a Menu is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuCreatedEvent {
    pub id: MenuId,
    pub data: MenuDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Menu is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuUpdatedEvent {
    pub id: MenuId,
    pub data: MenuDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Menu is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuDeletedEvent {
    pub id: MenuId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MENUBLOCK EVENTS
// ============================================================================

/// Event published when a MenuBlock is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockCreatedEvent {
    pub id: MenuBlockId,
    pub data: MenuBlockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MenuBlock is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockUpdatedEvent {
    pub id: MenuBlockId,
    pub data: MenuBlockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MenuBlock is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockDeletedEvent {
    pub id: MenuBlockId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PAGE EVENTS
// ============================================================================

/// Event published when a Page is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageCreatedEvent {
    pub id: PageId,
    pub data: PageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Page is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageUpdatedEvent {
    pub id: PageId,
    pub data: PageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Page is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageDeletedEvent {
    pub id: PageId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PAGEBLOCK EVENTS
// ============================================================================

/// Event published when a PageBlock is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockCreatedEvent {
    pub id: PageBlockId,
    pub data: PageBlockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PageBlock is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockUpdatedEvent {
    pub id: PageBlockId,
    pub data: PageBlockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PageBlock is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockDeletedEvent {
    pub id: PageBlockId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// REDIRECT EVENTS
// ============================================================================

/// Event published when a Redirect is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectCreatedEvent {
    pub id: RedirectId,
    pub data: RedirectDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Redirect is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectUpdatedEvent {
    pub id: RedirectId,
    pub data: RedirectDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Redirect is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectDeletedEvent {
    pub id: RedirectId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// VISITOR EVENTS
// ============================================================================

/// Event published when a Visitor is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorCreatedEvent {
    pub id: VisitorId,
    pub data: VisitorDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Visitor is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorUpdatedEvent {
    pub id: VisitorId,
    pub data: VisitorDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Visitor is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorDeletedEvent {
    pub id: VisitorId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// VISITORTRACK EVENTS
// ============================================================================

/// Event published when a VisitorTrack is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackCreatedEvent {
    pub id: VisitorTrackId,
    pub data: VisitorTrackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a VisitorTrack is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackUpdatedEvent {
    pub id: VisitorTrackId,
    pub data: VisitorTrackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a VisitorTrack is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackDeletedEvent {
    pub id: VisitorTrackId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// WEBSITE EVENTS
// ============================================================================

/// Event published when a Website is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteCreatedEvent {
    pub id: WebsiteId,
    pub data: WebsiteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Website is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteUpdatedEvent {
    pub id: WebsiteId,
    pub data: WebsiteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Website is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteDeletedEvent {
    pub id: WebsiteId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// WEBSITEAUDITLOG EVENTS
// ============================================================================

/// Event published when a WebsiteAuditLog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogCreatedEvent {
    pub id: WebsiteAuditLogId,
    pub data: WebsiteAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteAuditLog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogUpdatedEvent {
    pub id: WebsiteAuditLogId,
    pub data: WebsiteAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteAuditLog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogDeletedEvent {
    pub id: WebsiteAuditLogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// WEBSITEMEMBER EVENTS
// ============================================================================

/// Event published when a WebsiteMember is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberCreatedEvent {
    pub id: WebsiteMemberId,
    pub data: WebsiteMemberDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteMember is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberUpdatedEvent {
    pub id: WebsiteMemberId,
    pub data: WebsiteMemberDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteMember is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberDeletedEvent {
    pub id: WebsiteMemberId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Website module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WebsiteEvent {
    ContactMessageCreated(ContactMessageCreatedEvent),
    ContactMessageUpdated(ContactMessageUpdatedEvent),
    ContactMessageDeleted(ContactMessageDeletedEvent),
    MenuCreated(MenuCreatedEvent),
    MenuUpdated(MenuUpdatedEvent),
    MenuDeleted(MenuDeletedEvent),
    MenuBlockCreated(MenuBlockCreatedEvent),
    MenuBlockUpdated(MenuBlockUpdatedEvent),
    MenuBlockDeleted(MenuBlockDeletedEvent),
    PageCreated(PageCreatedEvent),
    PageUpdated(PageUpdatedEvent),
    PageDeleted(PageDeletedEvent),
    PageBlockCreated(PageBlockCreatedEvent),
    PageBlockUpdated(PageBlockUpdatedEvent),
    PageBlockDeleted(PageBlockDeletedEvent),
    RedirectCreated(RedirectCreatedEvent),
    RedirectUpdated(RedirectUpdatedEvent),
    RedirectDeleted(RedirectDeletedEvent),
    VisitorCreated(VisitorCreatedEvent),
    VisitorUpdated(VisitorUpdatedEvent),
    VisitorDeleted(VisitorDeletedEvent),
    VisitorTrackCreated(VisitorTrackCreatedEvent),
    VisitorTrackUpdated(VisitorTrackUpdatedEvent),
    VisitorTrackDeleted(VisitorTrackDeletedEvent),
    WebsiteCreated(WebsiteCreatedEvent),
    WebsiteUpdated(WebsiteUpdatedEvent),
    WebsiteDeleted(WebsiteDeletedEvent),
    WebsiteAuditLogCreated(WebsiteAuditLogCreatedEvent),
    WebsiteAuditLogUpdated(WebsiteAuditLogUpdatedEvent),
    WebsiteAuditLogDeleted(WebsiteAuditLogDeletedEvent),
    WebsiteMemberCreated(WebsiteMemberCreatedEvent),
    WebsiteMemberUpdated(WebsiteMemberUpdatedEvent),
    WebsiteMemberDeleted(WebsiteMemberDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for WebsiteEventMetadata {
    fn default() -> Self {
        Self {
            module: "website",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
