//! Website Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Website exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use website::exports::{ContactMessageDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ContactMessageDto` - Data transfer object for ContactMessage
/// - `ContactMessageSummary` - Summary view of ContactMessage
/// - `ContactMessageId` - Type-safe ID wrapper
/// - `MenuDto` - Data transfer object for Menu
/// - `MenuSummary` - Summary view of Menu
/// - `MenuId` - Type-safe ID wrapper
/// - `MenuBlockDto` - Data transfer object for MenuBlock
/// - `MenuBlockSummary` - Summary view of MenuBlock
/// - `MenuBlockId` - Type-safe ID wrapper
/// - `PageDto` - Data transfer object for Page
/// - `PageSummary` - Summary view of Page
/// - `PageId` - Type-safe ID wrapper
/// - `PageBlockDto` - Data transfer object for PageBlock
/// - `PageBlockSummary` - Summary view of PageBlock
/// - `PageBlockId` - Type-safe ID wrapper
/// - `RedirectDto` - Data transfer object for Redirect
/// - `RedirectSummary` - Summary view of Redirect
/// - `RedirectId` - Type-safe ID wrapper
/// - `VisitorDto` - Data transfer object for Visitor
/// - `VisitorSummary` - Summary view of Visitor
/// - `VisitorId` - Type-safe ID wrapper
/// - `VisitorTrackDto` - Data transfer object for VisitorTrack
/// - `VisitorTrackSummary` - Summary view of VisitorTrack
/// - `VisitorTrackId` - Type-safe ID wrapper
/// - `WebsiteDto` - Data transfer object for Website
/// - `WebsiteSummary` - Summary view of Website
/// - `WebsiteId` - Type-safe ID wrapper
/// - `WebsiteAuditLogDto` - Data transfer object for WebsiteAuditLog
/// - `WebsiteAuditLogSummary` - Summary view of WebsiteAuditLog
/// - `WebsiteAuditLogId` - Type-safe ID wrapper
/// - `WebsiteMemberDto` - Data transfer object for WebsiteMember
/// - `WebsiteMemberSummary` - Summary view of WebsiteMember
/// - `WebsiteMemberId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `ContactMessageCreatedEvent` - Published when ContactMessage is created
/// - `ContactMessageUpdatedEvent` - Published when ContactMessage is updated
/// - `ContactMessageDeletedEvent` - Published when ContactMessage is deleted
/// - `MenuCreatedEvent` - Published when Menu is created
/// - `MenuUpdatedEvent` - Published when Menu is updated
/// - `MenuDeletedEvent` - Published when Menu is deleted
/// - `MenuBlockCreatedEvent` - Published when MenuBlock is created
/// - `MenuBlockUpdatedEvent` - Published when MenuBlock is updated
/// - `MenuBlockDeletedEvent` - Published when MenuBlock is deleted
/// - `PageCreatedEvent` - Published when Page is created
/// - `PageUpdatedEvent` - Published when Page is updated
/// - `PageDeletedEvent` - Published when Page is deleted
/// - `PageBlockCreatedEvent` - Published when PageBlock is created
/// - `PageBlockUpdatedEvent` - Published when PageBlock is updated
/// - `PageBlockDeletedEvent` - Published when PageBlock is deleted
/// - `RedirectCreatedEvent` - Published when Redirect is created
/// - `RedirectUpdatedEvent` - Published when Redirect is updated
/// - `RedirectDeletedEvent` - Published when Redirect is deleted
/// - `VisitorCreatedEvent` - Published when Visitor is created
/// - `VisitorUpdatedEvent` - Published when Visitor is updated
/// - `VisitorDeletedEvent` - Published when Visitor is deleted
/// - `VisitorTrackCreatedEvent` - Published when VisitorTrack is created
/// - `VisitorTrackUpdatedEvent` - Published when VisitorTrack is updated
/// - `VisitorTrackDeletedEvent` - Published when VisitorTrack is deleted
/// - `WebsiteCreatedEvent` - Published when Website is created
/// - `WebsiteUpdatedEvent` - Published when Website is updated
/// - `WebsiteDeletedEvent` - Published when Website is deleted
/// - `WebsiteAuditLogCreatedEvent` - Published when WebsiteAuditLog is created
/// - `WebsiteAuditLogUpdatedEvent` - Published when WebsiteAuditLog is updated
/// - `WebsiteAuditLogDeletedEvent` - Published when WebsiteAuditLog is deleted
/// - `WebsiteMemberCreatedEvent` - Published when WebsiteMember is created
/// - `WebsiteMemberUpdatedEvent` - Published when WebsiteMember is updated
/// - `WebsiteMemberDeletedEvent` - Published when WebsiteMember is deleted
pub struct ExportSummary;
