//! Public types for Website module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// CONTACTMESSAGE TYPES
// ============================================================================

/// Type-safe ID for ContactMessage
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ContactMessageId(pub Uuid);

impl ContactMessageId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ContactMessageId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ContactMessageId> for Uuid {
    fn from(id: ContactMessageId) -> Self {
        id.0
    }
}

/// Data transfer object for ContactMessage
///
/// This is the public representation of ContactMessage for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageDto {
    pub id: ContactMessageId,
    pub website_id: Uuid,
    pub name: Option<String>,
    pub email: String,
    pub message: String,
    pub notified: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of ContactMessage for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageSummary {
    pub id: ContactMessageId,
    pub name: Option<String>,
    pub email: String,
}

/// Reference to ContactMessage for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessageRef {
    pub id: ContactMessageId,
}

// ============================================================================
// MENU TYPES
// ============================================================================

/// Type-safe ID for Menu
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MenuId(pub Uuid);

impl MenuId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MenuId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MenuId> for Uuid {
    fn from(id: MenuId) -> Self {
        id.0
    }
}

/// Data transfer object for Menu
///
/// This is the public representation of Menu for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuDto {
    pub id: MenuId,
    pub website_id: Uuid,
    pub parent_id: Option<Uuid>,
    pub name: String,
    pub page_id: Option<Uuid>,
    pub url: Option<String>,
    pub new_window: bool,
    pub sequence: i32,
    pub visibility: WebsiteVisibility,
    pub required_member_roles: Vec<String>,
    pub is_mega_menu: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Menu for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuSummary {
    pub id: MenuId,
    pub name: String,
}

/// Reference to Menu for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuRef {
    pub id: MenuId,
}

// ============================================================================
// MENUBLOCK TYPES
// ============================================================================

/// Type-safe ID for MenuBlock
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MenuBlockId(pub Uuid);

impl MenuBlockId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MenuBlockId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MenuBlockId> for Uuid {
    fn from(id: MenuBlockId) -> Self {
        id.0
    }
}

/// Data transfer object for MenuBlock
///
/// This is the public representation of MenuBlock for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockDto {
    pub id: MenuBlockId,
    pub menu_id: Uuid,
    pub kind: WebsiteMenuBlockKind,
    pub position: i32,
    pub payload: serde_json::Value,
}

/// Summary view of MenuBlock for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockSummary {
    pub id: MenuBlockId,
}

/// Reference to MenuBlock for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuBlockRef {
    pub id: MenuBlockId,
}

// ============================================================================
// PAGE TYPES
// ============================================================================

/// Type-safe ID for Page
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PageId(pub Uuid);

impl PageId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PageId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PageId> for Uuid {
    fn from(id: PageId) -> Self {
        id.0
    }
}

/// Data transfer object for Page
///
/// This is the public representation of Page for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageDto {
    pub id: PageId,
    pub key: String,
    pub website_id: Option<Uuid>,
    pub url: String,
    pub title: String,
    pub seo_name: Option<String>,
    pub is_published: bool,
    pub date_publish: Option<DateTime<Utc>>,
    pub website_indexed: bool,
    pub visibility: WebsiteVisibility,
    pub required_member_roles: Vec<String>,
    pub forked_from: Option<Uuid>,
    pub forked_at: Option<DateTime<Utc>>,
    pub forked_by: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Page for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageSummary {
    pub id: PageId,
    pub title: String,
    pub seo_name: Option<String>,
}

/// Reference to Page for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageRef {
    pub id: PageId,
}

// ============================================================================
// PAGEBLOCK TYPES
// ============================================================================

/// Type-safe ID for PageBlock
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PageBlockId(pub Uuid);

impl PageBlockId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PageBlockId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PageBlockId> for Uuid {
    fn from(id: PageBlockId) -> Self {
        id.0
    }
}

/// Data transfer object for PageBlock
///
/// This is the public representation of PageBlock for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockDto {
    pub id: PageBlockId,
    pub page_id: Uuid,
    pub kind: WebsitePageBlockKind,
    pub position: i32,
    pub payload: serde_json::Value,
}

/// Summary view of PageBlock for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockSummary {
    pub id: PageBlockId,
}

/// Reference to PageBlock for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageBlockRef {
    pub id: PageBlockId,
}

// ============================================================================
// REDIRECT TYPES
// ============================================================================

/// Type-safe ID for Redirect
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RedirectId(pub Uuid);

impl RedirectId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RedirectId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RedirectId> for Uuid {
    fn from(id: RedirectId) -> Self {
        id.0
    }
}

/// Data transfer object for Redirect
///
/// This is the public representation of Redirect for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectDto {
    pub id: RedirectId,
    pub website_id: Uuid,
    pub url_from: String,
    pub redirect_type: WebsiteRedirectType,
    pub url_to: Option<String>,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Redirect for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectSummary {
    pub id: RedirectId,
}

/// Reference to Redirect for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedirectRef {
    pub id: RedirectId,
}

// ============================================================================
// VISITOR TYPES
// ============================================================================

/// Type-safe ID for Visitor
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct VisitorId(pub Uuid);

impl VisitorId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for VisitorId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<VisitorId> for Uuid {
    fn from(id: VisitorId) -> Self {
        id.0
    }
}

/// Data transfer object for Visitor
///
/// This is the public representation of Visitor for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorDto {
    pub id: VisitorId,
    pub website_id: Uuid,
    pub access_token: String,
    pub kind: WebsiteVisitorKind,
    pub digest: String,
    pub digest_algo: String,
    pub portal_user_id: Option<Uuid>,
    pub country_code: Option<String>,
    pub visit_count: i32,
    pub last_connection_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of Visitor for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorSummary {
    pub id: VisitorId,
}

/// Reference to Visitor for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorRef {
    pub id: VisitorId,
}

// ============================================================================
// VISITORTRACK TYPES
// ============================================================================

/// Type-safe ID for VisitorTrack
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct VisitorTrackId(pub Uuid);

impl VisitorTrackId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for VisitorTrackId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<VisitorTrackId> for Uuid {
    fn from(id: VisitorTrackId) -> Self {
        id.0
    }
}

/// Data transfer object for VisitorTrack
///
/// This is the public representation of VisitorTrack for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackDto {
    pub id: VisitorTrackId,
    pub visitor_id: Uuid,
    pub page_id: Option<Uuid>,
    pub url: String,
    pub visited_at: DateTime<Utc>,
}

/// Summary view of VisitorTrack for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackSummary {
    pub id: VisitorTrackId,
}

/// Reference to VisitorTrack for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisitorTrackRef {
    pub id: VisitorTrackId,
}

// ============================================================================
// WEBSITE TYPES
// ============================================================================

/// Type-safe ID for Website
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WebsiteId(pub Uuid);

impl WebsiteId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WebsiteId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WebsiteId> for Uuid {
    fn from(id: WebsiteId) -> Self {
        id.0
    }
}

/// Data transfer object for Website
///
/// This is the public representation of Website for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteDto {
    pub id: WebsiteId,
    pub name: String,
    pub domain: Option<String>,
    pub company_id: Uuid,
    pub public_user_id: Uuid,
    pub default_lang_code: String,
    pub homepage_url: String,
    pub robots_txt: Option<String>,
    pub social_links: Option<serde_json::Value>,
    pub contact_recipients: Vec<String>,
    pub sequence: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of Website for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSummary {
    pub id: WebsiteId,
    pub name: String,
}

/// Reference to Website for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteRef {
    pub id: WebsiteId,
}

// ============================================================================
// WEBSITEAUDITLOG TYPES
// ============================================================================

/// Type-safe ID for WebsiteAuditLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WebsiteAuditLogId(pub Uuid);

impl WebsiteAuditLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WebsiteAuditLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WebsiteAuditLogId> for Uuid {
    fn from(id: WebsiteAuditLogId) -> Self {
        id.0
    }
}

/// Data transfer object for WebsiteAuditLog
///
/// This is the public representation of WebsiteAuditLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogDto {
    pub id: WebsiteAuditLogId,
    pub event: WebsiteAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    pub occurred_at: DateTime<Utc>,
}

/// Summary view of WebsiteAuditLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogSummary {
    pub id: WebsiteAuditLogId,
}

/// Reference to WebsiteAuditLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteAuditLogRef {
    pub id: WebsiteAuditLogId,
}

// ============================================================================
// WEBSITEMEMBER TYPES
// ============================================================================

/// Type-safe ID for WebsiteMember
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WebsiteMemberId(pub Uuid);

impl WebsiteMemberId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WebsiteMemberId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WebsiteMemberId> for Uuid {
    fn from(id: WebsiteMemberId) -> Self {
        id.0
    }
}

/// Data transfer object for WebsiteMember
///
/// This is the public representation of WebsiteMember for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberDto {
    pub id: WebsiteMemberId,
    pub website_id: Uuid,
    pub portal_user_id: Uuid,
    pub role: WebsiteMemberRole,
    pub metadata: serde_json::Value,
}

/// Summary view of WebsiteMember for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberSummary {
    pub id: WebsiteMemberId,
}

/// Reference to WebsiteMember for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteMemberRef {
    pub id: WebsiteMemberId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
