//! Application layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This layer contains:
//! - Commands (CQRS write operations)
//! - Queries (CQRS read operations)
//! - Services (business logic)
//! - Middleware (Auth & RBAC)
//! - Triggers (lifecycle hooks)
//! - Validation (input validation)
//! - Workflows (saga/orchestration patterns)

pub mod service;
pub mod validator;

// Re-exports
pub use service::*;
// <<< CUSTOM
// END CUSTOM
