//! Website Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ContactMessageService;
pub use application::service::MenuService;
pub use application::service::MenuBlockService;
pub use application::service::PageService;
pub use application::service::PageBlockService;
pub use application::service::RedirectService;
pub use application::service::VisitorService;
pub use application::service::VisitorTrackService;
pub use application::service::WebsiteService;
pub use application::service::WebsiteAuditLogService;
pub use application::service::WebsiteMemberService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Website module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let website = WebsiteModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = website.all_crud_routes();
/// ```
pub struct WebsiteModule {
    pub(crate) contact_message_service: Arc<ContactMessageService>,
    pub(crate) menu_service: Arc<MenuService>,
    pub(crate) menu_block_service: Arc<MenuBlockService>,
    pub(crate) page_service: Arc<PageService>,
    pub(crate) page_block_service: Arc<PageBlockService>,
    pub(crate) redirect_service: Arc<RedirectService>,
    pub(crate) visitor_service: Arc<VisitorService>,
    pub(crate) visitor_track_service: Arc<VisitorTrackService>,
    pub(crate) website_service: Arc<WebsiteService>,
    pub(crate) website_audit_log_service: Arc<WebsiteAuditLogService>,
    pub(crate) website_member_service: Arc<WebsiteMemberService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl WebsiteModule {
    /// Create a new module builder
    pub fn builder() -> WebsiteModuleBuilder {
        WebsiteModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_contact_message_read_routes,
            create_menu_read_routes,
            create_menu_block_read_routes,
            create_page_read_routes,
            create_page_block_read_routes,
            create_redirect_read_routes,
            create_visitor_read_routes,
            create_visitor_track_read_routes,
            create_website_read_routes,
            create_website_audit_log_read_routes,
            create_website_member_read_routes,
        };

        Router::new()
            .merge(create_contact_message_read_routes(self.contact_message_service.clone()))
            .merge(create_menu_read_routes(self.menu_service.clone()))
            .merge(create_menu_block_read_routes(self.menu_block_service.clone()))
            .merge(create_page_read_routes(self.page_service.clone()))
            .merge(create_page_block_read_routes(self.page_block_service.clone()))
            .merge(create_redirect_read_routes(self.redirect_service.clone()))
            .merge(create_visitor_read_routes(self.visitor_service.clone()))
            .merge(create_visitor_track_read_routes(self.visitor_track_service.clone()))
            .merge(create_website_read_routes(self.website_service.clone()))
            .merge(create_website_audit_log_read_routes(self.website_audit_log_service.clone()))
            .merge(create_website_member_read_routes(self.website_member_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_contact_message_read_routes,
            create_menu_read_routes,
            create_menu_block_read_routes,
            create_page_read_routes,
            create_page_block_read_routes,
            create_redirect_read_routes,
            create_visitor_read_routes,
            create_visitor_track_read_routes,
            create_website_read_routes,
            create_website_audit_log_read_routes,
            create_website_member_read_routes,
        };

        Router::new()
            .merge(create_contact_message_read_routes(self.contact_message_service.clone()))
            .merge(create_menu_read_routes(self.menu_service.clone()))
            .merge(create_menu_block_read_routes(self.menu_block_service.clone()))
            .merge(create_page_read_routes(self.page_service.clone()))
            .merge(create_page_block_read_routes(self.page_block_service.clone()))
            .merge(create_redirect_read_routes(self.redirect_service.clone()))
            .merge(create_visitor_read_routes(self.visitor_service.clone()))
            .merge(create_visitor_track_read_routes(self.visitor_track_service.clone()))
            .merge(create_website_read_routes(self.website_service.clone()))
            .merge(create_website_audit_log_read_routes(self.website_audit_log_service.clone()))
            .merge(create_website_member_read_routes(self.website_member_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for WebsiteModule
pub struct WebsiteModuleBuilder {
    db_pool: Option<PgPool>,
}

impl WebsiteModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<WebsiteModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // ContactMessage service
        let contact_message_repository = Arc::new(ContactMessageRepository::new(db_pool.clone()));
        let contact_message_service = Arc::new(ContactMessageService::with_repository(contact_message_repository.clone()));

        // Menu service
        let menu_repository = Arc::new(MenuRepository::new(db_pool.clone()));
        let menu_service = Arc::new(MenuService::with_repository(menu_repository.clone()));

        // MenuBlock service
        let menu_block_repository = Arc::new(MenuBlockRepository::new(db_pool.clone()));
        let menu_block_service = Arc::new(MenuBlockService::with_repository(menu_block_repository.clone()));

        // Page service
        let page_repository = Arc::new(PageRepository::new(db_pool.clone()));
        let page_service = Arc::new(PageService::with_repository(page_repository.clone()));

        // PageBlock service
        let page_block_repository = Arc::new(PageBlockRepository::new(db_pool.clone()));
        let page_block_service = Arc::new(PageBlockService::with_repository(page_block_repository.clone()));

        // Redirect service
        let redirect_repository = Arc::new(RedirectRepository::new(db_pool.clone()));
        let redirect_service = Arc::new(RedirectService::with_repository(redirect_repository.clone()));

        // Visitor service
        let visitor_repository = Arc::new(VisitorRepository::new(db_pool.clone()));
        let visitor_service = Arc::new(VisitorService::with_repository(visitor_repository.clone()));

        // VisitorTrack service
        let visitor_track_repository = Arc::new(VisitorTrackRepository::new(db_pool.clone()));
        let visitor_track_service = Arc::new(VisitorTrackService::with_repository(visitor_track_repository.clone()));

        // Website service
        let website_repository = Arc::new(WebsiteRepository::new(db_pool.clone()));
        let website_service = Arc::new(WebsiteService::with_repository(website_repository.clone()));

        // WebsiteAuditLog service
        let website_audit_log_repository = Arc::new(WebsiteAuditLogRepository::new(db_pool.clone()));
        let website_audit_log_service = Arc::new(WebsiteAuditLogService::with_repository(website_audit_log_repository.clone()));

        // WebsiteMember service
        let website_member_repository = Arc::new(WebsiteMemberRepository::new(db_pool.clone()));
        let website_member_service = Arc::new(WebsiteMemberService::with_repository(website_member_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(WebsiteModule {
            contact_message_service,
            menu_service,
            menu_block_service,
            page_service,
            page_block_service,
            redirect_service,
            visitor_service,
            visitor_track_service,
            website_service,
            website_audit_log_service,
            website_member_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for WebsiteModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
