//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod contact_message_handler;
pub mod menu_handler;
pub mod menu_block_handler;
pub mod page_handler;
pub mod page_block_handler;
pub mod redirect_handler;
pub mod visitor_handler;
pub mod visitor_track_handler;
pub mod website_handler;
pub mod website_audit_log_handler;
pub mod website_member_handler;

// <<< CUSTOM
pub mod admin_routes;
pub mod public_routes;
// END CUSTOM

// Re-exports
pub use contact_message_handler::{create_contact_message_routes, create_contact_message_read_routes, create_contact_message_write_routes};
pub use menu_handler::{create_menu_routes, create_menu_read_routes, create_menu_write_routes};
pub use menu_block_handler::{create_menu_block_routes, create_menu_block_read_routes, create_menu_block_write_routes};
pub use page_handler::{create_page_routes, create_page_read_routes, create_page_write_routes};
pub use page_block_handler::{create_page_block_routes, create_page_block_read_routes, create_page_block_write_routes};
pub use redirect_handler::{create_redirect_routes, create_redirect_read_routes, create_redirect_write_routes};
pub use visitor_handler::{create_visitor_routes, create_visitor_read_routes, create_visitor_write_routes};
pub use visitor_track_handler::{create_visitor_track_routes, create_visitor_track_read_routes, create_visitor_track_write_routes};
pub use website_handler::{create_website_routes, create_website_read_routes, create_website_write_routes};
pub use website_audit_log_handler::{create_website_audit_log_routes, create_website_audit_log_read_routes, create_website_audit_log_write_routes};
pub use website_member_handler::{create_website_member_routes, create_website_member_read_routes, create_website_member_write_routes};
// <<< CUSTOM
pub use admin_routes::{website_admin_routes, WebsiteAdminState, WebsiteActor};
pub use public_routes::{website_public_routes, WebsitePublicState};
// END CUSTOM
